services:
  backend:
    image: ghcr.io/sdarius22/music-player-project/music-player-backend:latest
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=pg-master
      - DB_PORT=5432
      - DB_NAME=music_db
      - DB_USER=music_admin
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REDIS_HOST=redis
    volumes:
      - /home/deployer/music-player/music_data:/root/music-server
    networks:
      - backend-net
    depends_on:
      - pg-master
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  pg-master:
    image: postgres:18
    environment:
      - POSTGRES_USER=music_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=music_db
    volumes:
      - /home/deployer/music-player/postgres_data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - backend-net

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    driver: overlay