services:
  backend:
    image: ghcr.io/sdarius22/music-player-project/music-player-backend:latest
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=pg-master
      - DB_PORT=5432
      - DB_NAME=music_db
      - DB_USER=music_admin
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REDIS_HOST=redis
    volumes:
      - /home/deployer/music-player/music_data:/root/music-server
    networks:
      - backend-net
    depends_on:
      - pg-master
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  pg-master:
    image: postgres:18
    environment:
      - POSTGRES_USER=music_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=music_db
    volumes:
      - /home/deployer/music-player/postgres_data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - backend-net

  pg-slave:
    image: postgres:18
    user: postgres
    environment:
      - POSTGRES_USER=music_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - /home/deployer/music-player/postgres_slave:/var/lib/postgresql/data
      - /home/deployer/music-player/pg-slave-init.sh:/pg-slave-init.sh
    command: bash /pg-slave-init.sh
    restart: unless-stopped
    depends_on:
      - pg-master
    networks:
      - backend-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=darius.sala@bt-app.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    restart: unless-stopped
    networks:
      - backend-net

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend-net

  goaccess:
    image: allinurl/goaccess
    volumes:
      - /var/log/nginx:/srv/logs:ro
      - /home/deployer/music-player/goaccess-report:/srv/report
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "127.0.0.1:7890:443"
    command: [
      "/srv/logs/access.log",
      "--output=/srv/report/index.html",
      "--real-time-html",
      "--ws-url=wss://www.bt-app.com/goaccess-ws",
      "--port=443",
      "--log-format=COMBINED",
      "--origin=https://www.bt-app.com",
      "--ssl-cert=/etc/letsencrypt/live/www.bt-app.com/fullchain.pem",
      "--ssl-key=/etc/letsencrypt/live/www.bt-app.com/privkey.pem"
    ]
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    driver: overlay