// Mocks generated by Mockito 5.4.6 from annotations
// in music_player_frontend/test/core/services/album_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i11;
import 'dart:typed_data' as _i10;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:music_player_frontend/core/dtos/album_page_dto.dart' as _i4;
import 'package:music_player_frontend/core/entities/album.dart' as _i2;
import 'package:music_player_frontend/core/repository/interfaces/album_repository.dart'
    as _i6;
import 'package:music_player_frontend/core/services/rest_clients/album_rest_service.dart'
    as _i8;
import 'package:music_player_frontend/core/services/rest_clients/auth_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAlbum_0 extends _i1.SmartFake implements _i2.Album {
  _FakeAlbum_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlbumPageDto_2 extends _i1.SmartFake implements _i4.AlbumPageDto {
  _FakeAlbumPageDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AlbumRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumRepository extends _i1.Mock implements _i6.AlbumRepository {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.Stream<dynamic> watchAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbums, []),
            returnValue: _i7.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i7.Stream<dynamic>.empty(),
          )
          as _i7.Stream<dynamic>);

  @override
  _i2.Album saveAlbum(_i2.Album? album) =>
      (super.noSuchMethod(
            Invocation.method(#saveAlbum, [album]),
            returnValue: _FakeAlbum_0(
              this,
              Invocation.method(#saveAlbum, [album]),
            ),
            returnValueForMissingStub: _FakeAlbum_0(
              this,
              Invocation.method(#saveAlbum, [album]),
            ),
          )
          as _i2.Album);

  @override
  _i2.Album? getAlbum(int? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [albumId]),
            returnValueForMissingStub: null,
          )
          as _i2.Album?);

  @override
  _i2.Album? getAlbumByName(String? albumName) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumByName, [albumName]),
            returnValueForMissingStub: null,
          )
          as _i2.Album?);

  @override
  _i2.Album? getAlbumByServerId(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumByServerId, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i2.Album?);

  @override
  List<_i2.Album> getAlbums(
    String? query,
    String? sortField,
    bool? ascending,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbums, [query, sortField, ascending]),
            returnValue: <_i2.Album>[],
            returnValueForMissingStub: <_i2.Album>[],
          )
          as List<_i2.Album>);

  @override
  List<_i2.Album> getAlbumsPaged(
    String? query,
    String? sortField,
    bool? ascending,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumsPaged, [
              query,
              sortField,
              ascending,
              offset,
              limit,
            ]),
            returnValue: <_i2.Album>[],
            returnValueForMissingStub: <_i2.Album>[],
          )
          as List<_i2.Album>);

  @override
  List<_i2.Album> getAllAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlbums, []),
            returnValue: <_i2.Album>[],
            returnValueForMissingStub: <_i2.Album>[],
          )
          as List<_i2.Album>);

  @override
  void updateAlbum(_i2.Album? album) => super.noSuchMethod(
    Invocation.method(#updateAlbum, [album]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AlbumRestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumRestService extends _i1.Mock implements _i8.AlbumRestService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set authService(_i3.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i4.AlbumPageDto> getAlbumsPage({
    String? query,
    int? page = 0,
    int? size = 30,
    String? sort = 'name,asc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumsPage, [], {
              #query: query,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue: _i7.Future<_i4.AlbumPageDto>.value(
              _FakeAlbumPageDto_2(
                this,
                Invocation.method(#getAlbumsPage, [], {
                  #query: query,
                  #page: page,
                  #size: size,
                  #sort: sort,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.AlbumPageDto>.value(
              _FakeAlbumPageDto_2(
                this,
                Invocation.method(#getAlbumsPage, [], {
                  #query: query,
                  #page: page,
                  #size: size,
                  #sort: sort,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.AlbumPageDto>);

  @override
  _i7.Future<_i10.Uint8List?> getAlbumCover(int? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumCover, [albumId]),
            returnValue: _i7.Future<_i10.Uint8List?>.value(),
            returnValueForMissingStub: _i7.Future<_i10.Uint8List?>.value(),
          )
          as _i7.Future<_i10.Uint8List?>);

  @override
  _i7.Future<_i5.Response> post(String? endpoint, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(String? endpoint, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> multipartRequest(
    String? method,
    String? endpoint, {
    Map<String, String>? fields,
    List<_i5.MultipartFile>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [method, endpoint],
              {#fields: fields, #files: files},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> multipartRequestWithProgress(
    String? method,
    String? endpoint,
    _i11.File? file,
    Map<String, String>? fields,
    void Function(int, int)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#multipartRequestWithProgress, [
              method,
              endpoint,
              file,
              fields,
              onProgress,
            ]),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);
}
