// Mocks generated by Mockito 5.4.6 from annotations
// in music_player_frontend/test/core/services/app_audio_service_playback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i20;
import 'dart:typed_data' as _i14;

import 'package:audio_session/audio_session.dart' as _i21;
import 'package:http/http.dart' as _i7;
import 'package:just_audio/just_audio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:music_player_frontend/core/dtos/playback_state_dto.dart'
    as _i19;
import 'package:music_player_frontend/core/dtos/playlists/playlist_detail_dto.dart'
    as _i16;
import 'package:music_player_frontend/core/dtos/playlists/playlist_dto.dart'
    as _i15;
import 'package:music_player_frontend/core/dtos/songs/song_dto.dart' as _i11;
import 'package:music_player_frontend/core/entities/app_settings.dart' as _i4;
import 'package:music_player_frontend/core/entities/audio_settings.dart' as _i3;
import 'package:music_player_frontend/core/entities/playlist.dart' as _i5;
import 'package:music_player_frontend/core/entities/song.dart' as _i2;
import 'package:music_player_frontend/core/rest_clients/auth_service.dart'
    as _i6;
import 'package:music_player_frontend/core/rest_clients/playback_rest_client.dart'
    as _i18;
import 'package:music_player_frontend/core/services/playlist_service.dart'
    as _i13;
import 'package:music_player_frontend/core/services/settings_service.dart'
    as _i12;
import 'package:music_player_frontend/core/services/song_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSong_0 extends _i1.SmartFake implements _i2.Song {
  _FakeSong_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioSettings_1 extends _i1.SmartFake implements _i3.AudioSettings {
  _FakeAudioSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_2 extends _i1.SmartFake implements _i4.AppSettings {
  _FakeAppSettings_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylist_3 extends _i1.SmartFake implements _i5.Playlist {
  _FakePlaylist_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_4 extends _i1.SmartFake implements _i6.AuthService {
  _FakeAuthService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerEvent_6 extends _i1.SmartFake implements _i8.PlayerEvent {
  _FakePlayerEvent_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackEvent_7 extends _i1.SmartFake implements _i8.PlaybackEvent {
  _FakePlaybackEvent_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_8 extends _i1.SmartFake implements Duration {
  _FakeDuration_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerState_9 extends _i1.SmartFake implements _i8.PlayerState {
  _FakePlayerState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSequenceState_10 extends _i1.SmartFake implements _i8.SequenceState {
  _FakeSequenceState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SongService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongService extends _i1.Mock implements _i9.SongService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Stream<dynamic> get watchSongs =>
      (super.noSuchMethod(
            Invocation.getter(#watchSongs),
            returnValue: _i10.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i10.Stream<dynamic>.empty(),
          )
          as _i10.Stream<dynamic>);

  @override
  _i2.Song? getLocalSong(String? songHash) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSong, [songHash]),
            returnValueForMissingStub: null,
          )
          as _i2.Song?);

  @override
  _i2.Song getOrCreateSong(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateSong, [fileHash]),
            returnValue: _FakeSong_0(
              this,
              Invocation.method(#getOrCreateSong, [fileHash]),
            ),
            returnValueForMissingStub: _FakeSong_0(
              this,
              Invocation.method(#getOrCreateSong, [fileHash]),
            ),
          )
          as _i2.Song);

  @override
  _i10.Future<_i2.Song?> fetchSongByFileHash(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSongByFileHash, [fileHash]),
            returnValue: _i10.Future<_i2.Song?>.value(),
            returnValueForMissingStub: _i10.Future<_i2.Song?>.value(),
          )
          as _i10.Future<_i2.Song?>);

  @override
  _i10.Future<List<_i2.Song>> fullyFetchSongs(List<_i2.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#fullyFetchSongs, [songs]),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<_i2.Song> fullyFetchSong(_i2.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#fullyFetchSong, [song]),
            returnValue: _i10.Future<_i2.Song>.value(
              _FakeSong_0(this, Invocation.method(#fullyFetchSong, [song])),
            ),
            returnValueForMissingStub: _i10.Future<_i2.Song>.value(
              _FakeSong_0(this, Invocation.method(#fullyFetchSong, [song])),
            ),
          )
          as _i10.Future<_i2.Song>);

  @override
  _i10.Future<void> updateSong(_i2.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#updateSong, [song]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void updateSongsBatch(List<_i2.Song>? songs) => super.noSuchMethod(
    Invocation.method(#updateSongsBatch, [songs]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteSong(_i2.Song? song) => super.noSuchMethod(
    Invocation.method(#deleteSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<({List<_i2.Song> content, int page, int totalPages})>
  getSongsPage(
    String? query,
    String? sortField,
    bool? ascending,
    bool? localOnly,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsPage, [
              query,
              sortField,
              ascending,
              localOnly,
              page,
              pageSize,
            ]),
            returnValue: _i10.Future<
              ({List<_i2.Song> content, int page, int totalPages})
            >.value((content: <_i2.Song>[], page: 0, totalPages: 0)),
            returnValueForMissingStub: _i10.Future<
              ({List<_i2.Song> content, int page, int totalPages})
            >.value((content: <_i2.Song>[], page: 0, totalPages: 0)),
          )
          as _i10.Future<({List<_i2.Song> content, int page, int totalPages})>);

  @override
  _i10.Future<List<_i2.Song>> getRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, []),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<List<_i2.Song>> getForgottenFavourites() =>
      (super.noSuchMethod(
            Invocation.method(#getForgottenFavourites, []),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<List<_i2.Song>> getQuickDial() =>
      (super.noSuchMethod(
            Invocation.method(#getQuickDial, []),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<List<_i2.Song>> getFavoriteSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteSongs, []),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<List<_i2.Song>> getMostPlayedSongs(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getMostPlayedSongs, [limit]),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  _i10.Future<List<_i2.Song>> getRecentlyPlayedSongs(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayedSongs, [limit]),
            returnValue: _i10.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i10.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i10.Future<List<_i2.Song>>);

  @override
  List<_i2.Song> cacheServerSongs(List<_i11.SongDto>? serverSongs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerSongs, [serverSongs]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i12.SettingsService {
  @override
  _i10.Future<_i3.AudioSettings> getAudioSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioSettings, []),
            returnValue: _i10.Future<_i3.AudioSettings>.value(
              _FakeAudioSettings_1(
                this,
                Invocation.method(#getAudioSettings, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i3.AudioSettings>.value(
              _FakeAudioSettings_1(
                this,
                Invocation.method(#getAudioSettings, []),
              ),
            ),
          )
          as _i10.Future<_i3.AudioSettings>);

  @override
  _i10.Future<void> updateAudioSettings(_i3.AudioSettings? newSettings) =>
      (super.noSuchMethod(
            Invocation.method(#updateAudioSettings, [newSettings]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i4.AppSettings getAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAppSettings, []),
            returnValue: _FakeAppSettings_2(
              this,
              Invocation.method(#getAppSettings, []),
            ),
            returnValueForMissingStub: _FakeAppSettings_2(
              this,
              Invocation.method(#getAppSettings, []),
            ),
          )
          as _i4.AppSettings);

  @override
  void updateAppSettings(_i4.AppSettings? newSettings) => super.noSuchMethod(
    Invocation.method(#updateAppSettings, [newSettings]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PlaylistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistService extends _i1.Mock implements _i13.PlaylistService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Stream<dynamic> watchPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#watchPlaylists, []),
            returnValue: _i10.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i10.Stream<dynamic>.empty(),
          )
          as _i10.Stream<dynamic>);

  @override
  _i10.Future<_i5.Playlist> addPlaylist(
    String? name,
    List<_i2.Song>? songs,
    _i14.Uint8List? coverArt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPlaylist, [name, songs, coverArt]),
            returnValue: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#addPlaylist, [name, songs, coverArt]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#addPlaylist, [name, songs, coverArt]),
              ),
            ),
          )
          as _i10.Future<_i5.Playlist>);

  @override
  _i10.Future<_i5.Playlist> updatePlaylist(_i5.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlist]),
            returnValue: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#updatePlaylist, [playlist]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#updatePlaylist, [playlist]),
              ),
            ),
          )
          as _i10.Future<_i5.Playlist>);

  @override
  _i10.Future<_i2.Song?> getMostRecentPlayedSong() =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentPlayedSong, []),
            returnValue: _i10.Future<_i2.Song?>.value(),
            returnValueForMissingStub: _i10.Future<_i2.Song?>.value(),
          )
          as _i10.Future<_i2.Song?>);

  @override
  _i10.Future<_i5.Playlist> getPlaylistByName(
    String? name, {
    bool? indestructible = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlaylistByName,
              [name],
              {#indestructible: indestructible},
            ),
            returnValue: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(
                  #getPlaylistByName,
                  [name],
                  {#indestructible: indestructible},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(
                  #getPlaylistByName,
                  [name],
                  {#indestructible: indestructible},
                ),
              ),
            ),
          )
          as _i10.Future<_i5.Playlist>);

  @override
  _i10.Future<({List<_i5.Playlist> content, int page, int totalPages})>
  getIndestructiblePlaylists(int? page, int? size) =>
      (super.noSuchMethod(
            Invocation.method(#getIndestructiblePlaylists, [page, size]),
            returnValue: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
            returnValueForMissingStub: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
          )
          as _i10.Future<
            ({List<_i5.Playlist> content, int page, int totalPages})
          >);

  @override
  _i10.Future<({List<_i5.Playlist> content, int page, int totalPages})>
  getNormalPlaylists(int? page, int? size) =>
      (super.noSuchMethod(
            Invocation.method(#getNormalPlaylists, [page, size]),
            returnValue: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
            returnValueForMissingStub: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
          )
          as _i10.Future<
            ({List<_i5.Playlist> content, int page, int totalPages})
          >);

  @override
  _i10.Future<({List<_i5.Playlist> content, int page, int totalPages})>
  getPlaylistsPage(
    String? query,
    String? sortField,
    bool? ascending,
    bool? containLocalOnly,
    int? page,
    int? size,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistsPage, [
              query,
              sortField,
              ascending,
              containLocalOnly,
              page,
              size,
            ]),
            returnValue: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
            returnValueForMissingStub: _i10.Future<
              ({List<_i5.Playlist> content, int page, int totalPages})
            >.value((content: <_i5.Playlist>[], page: 0, totalPages: 0)),
          )
          as _i10.Future<
            ({List<_i5.Playlist> content, int page, int totalPages})
          >);

  @override
  _i10.Future<_i5.Playlist> getPlaylistDetails(_i5.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistDetails, [playlist]),
            returnValue: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#getPlaylistDetails, [playlist]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#getPlaylistDetails, [playlist]),
              ),
            ),
          )
          as _i10.Future<_i5.Playlist>);

  @override
  _i10.Future<_i5.Playlist> addToPlaylist(
    _i5.Playlist? playlist,
    List<_i2.Song>? songs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToPlaylist, [playlist, songs]),
            returnValue: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#addToPlaylist, [playlist, songs]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.Playlist>.value(
              _FakePlaylist_3(
                this,
                Invocation.method(#addToPlaylist, [playlist, songs]),
              ),
            ),
          )
          as _i10.Future<_i5.Playlist>);

  @override
  _i10.Future<void> deleteFromPlaylist(
    _i2.Song? song,
    _i5.Playlist? playlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromPlaylist, [song, playlist]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deletePlaylist(_i5.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlist]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i5.Playlist cacheServerPlaylist(_i15.PlaylistDto? serverPlaylist) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            returnValue: _FakePlaylist_3(
              this,
              Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            ),
            returnValueForMissingStub: _FakePlaylist_3(
              this,
              Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            ),
          )
          as _i5.Playlist);

  @override
  _i5.Playlist cacheServerPlaylistDetails(
    _i16.PlaylistDetailDto? serverPlaylist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerPlaylistDetails, [serverPlaylist]),
            returnValue: _FakePlaylist_3(
              this,
              Invocation.method(#cacheServerPlaylistDetails, [serverPlaylist]),
            ),
            returnValueForMissingStub: _FakePlaylist_3(
              this,
              Invocation.method(#cacheServerPlaylistDetails, [serverPlaylist]),
            ),
          )
          as _i5.Playlist);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<String?> get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _i10.Future<String?>.value(),
            returnValueForMissingStub: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void startTokenRefresh() => super.noSuchMethod(
    Invocation.method(#startTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopTokenRefresh() => super.noSuchMethod(
    Invocation.method(#stopTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> saveTokens(String? access, String? refresh) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [access, refresh]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> sendLoginCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendLoginCode, [email]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> verifyCode(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [email, code]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<String?> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i10.Future<String?>.value(),
            returnValueForMissingStub: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<bool> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [PlaybackRestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackRestClient extends _i1.Mock
    implements _i18.PlaybackRestClient {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_4(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_4(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i6.AuthService);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set authService(_i6.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i19.PlaybackStateDto?> getPlaybackState() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackState, []),
            returnValue: _i10.Future<_i19.PlaybackStateDto?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i19.PlaybackStateDto?>.value(),
          )
          as _i10.Future<_i19.PlaybackStateDto?>);

  @override
  _i10.Future<void> savePlaybackState(_i19.PlaybackStateDto? state) =>
      (super.noSuchMethod(
            Invocation.method(#savePlaybackState, [state]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.Response> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#post, [endpoint, body])),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#post, [endpoint, body])),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> get(
    String? endpoint, {
    Map<String, String>? headers = const {'Content-Type': 'application/json'},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint], {#headers: headers}),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#get, [endpoint], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#get, [endpoint], {#headers: headers}),
              ),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> patch(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [endpoint, body]),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#patch, [endpoint, body]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#patch, [endpoint, body]),
              ),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> put(String? endpoint, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#put, [endpoint, body])),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#put, [endpoint, body])),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#delete, [endpoint])),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(this, Invocation.method(#delete, [endpoint])),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> multipartRequest(
    String? method,
    String? endpoint, {
    Map<String, String>? fields,
    List<_i7.MultipartFile>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [method, endpoint],
              {#fields: fields, #files: files},
            ),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response>);

  @override
  _i10.Future<_i7.Response> multipartRequestWithProgress(
    String? method,
    String? endpoint,
    _i20.File? file,
    Map<String, String>? fields,
    void Function(int, int)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#multipartRequestWithProgress, [
              method,
              endpoint,
              file,
              fields,
              onProgress,
            ]),
            returnValue: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.Response>.value(
              _FakeResponse_5(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i10.Future<_i7.Response>);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i8.AudioPlayer {
  @override
  _i8.PlayerEvent get playerEvent =>
      (super.noSuchMethod(
            Invocation.getter(#playerEvent),
            returnValue: _FakePlayerEvent_6(
              this,
              Invocation.getter(#playerEvent),
            ),
            returnValueForMissingStub: _FakePlayerEvent_6(
              this,
              Invocation.getter(#playerEvent),
            ),
          )
          as _i8.PlayerEvent);

  @override
  _i10.Stream<_i8.PlayerEvent> get playerEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerEventStream),
            returnValue: _i10.Stream<_i8.PlayerEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.PlayerEvent>.empty(),
          )
          as _i10.Stream<_i8.PlayerEvent>);

  @override
  _i8.PlaybackEvent get playbackEvent =>
      (super.noSuchMethod(
            Invocation.getter(#playbackEvent),
            returnValue: _FakePlaybackEvent_7(
              this,
              Invocation.getter(#playbackEvent),
            ),
            returnValueForMissingStub: _FakePlaybackEvent_7(
              this,
              Invocation.getter(#playbackEvent),
            ),
          )
          as _i8.PlaybackEvent);

  @override
  _i10.Stream<_i8.PlaybackEvent> get playbackEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackEventStream),
            returnValue: _i10.Stream<_i8.PlaybackEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.PlaybackEvent>.empty(),
          )
          as _i10.Stream<_i8.PlaybackEvent>);

  @override
  _i10.Stream<Duration?> get durationStream =>
      (super.noSuchMethod(
            Invocation.getter(#durationStream),
            returnValue: _i10.Stream<Duration?>.empty(),
            returnValueForMissingStub: _i10.Stream<Duration?>.empty(),
          )
          as _i10.Stream<Duration?>);

  @override
  _i8.ProcessingState get processingState =>
      (super.noSuchMethod(
            Invocation.getter(#processingState),
            returnValue: _i8.ProcessingState.idle,
            returnValueForMissingStub: _i8.ProcessingState.idle,
          )
          as _i8.ProcessingState);

  @override
  _i10.Stream<_i8.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#processingStateStream),
            returnValue: _i10.Stream<_i8.ProcessingState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.ProcessingState>.empty(),
          )
          as _i10.Stream<_i8.ProcessingState>);

  @override
  bool get playing =>
      (super.noSuchMethod(
            Invocation.getter(#playing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Stream<bool> get playingStream =>
      (super.noSuchMethod(
            Invocation.getter(#playingStream),
            returnValue: _i10.Stream<bool>.empty(),
            returnValueForMissingStub: _i10.Stream<bool>.empty(),
          )
          as _i10.Stream<bool>);

  @override
  double get volume =>
      (super.noSuchMethod(
            Invocation.getter(#volume),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i10.Stream<double> get volumeStream =>
      (super.noSuchMethod(
            Invocation.getter(#volumeStream),
            returnValue: _i10.Stream<double>.empty(),
            returnValueForMissingStub: _i10.Stream<double>.empty(),
          )
          as _i10.Stream<double>);

  @override
  double get speed =>
      (super.noSuchMethod(
            Invocation.getter(#speed),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i10.Stream<double> get speedStream =>
      (super.noSuchMethod(
            Invocation.getter(#speedStream),
            returnValue: _i10.Stream<double>.empty(),
            returnValueForMissingStub: _i10.Stream<double>.empty(),
          )
          as _i10.Stream<double>);

  @override
  double get pitch =>
      (super.noSuchMethod(
            Invocation.getter(#pitch),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i10.Stream<double> get pitchStream =>
      (super.noSuchMethod(
            Invocation.getter(#pitchStream),
            returnValue: _i10.Stream<double>.empty(),
            returnValueForMissingStub: _i10.Stream<double>.empty(),
          )
          as _i10.Stream<double>);

  @override
  bool get skipSilenceEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#skipSilenceEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Stream<bool> get skipSilenceEnabledStream =>
      (super.noSuchMethod(
            Invocation.getter(#skipSilenceEnabledStream),
            returnValue: _i10.Stream<bool>.empty(),
            returnValueForMissingStub: _i10.Stream<bool>.empty(),
          )
          as _i10.Stream<bool>);

  @override
  Duration get bufferedPosition =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPosition),
            returnValue: _FakeDuration_8(
              this,
              Invocation.getter(#bufferedPosition),
            ),
            returnValueForMissingStub: _FakeDuration_8(
              this,
              Invocation.getter(#bufferedPosition),
            ),
          )
          as Duration);

  @override
  _i10.Stream<Duration> get bufferedPositionStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionStream),
            returnValue: _i10.Stream<Duration>.empty(),
            returnValueForMissingStub: _i10.Stream<Duration>.empty(),
          )
          as _i10.Stream<Duration>);

  @override
  _i10.Stream<_i8.IcyMetadata?> get icyMetadataStream =>
      (super.noSuchMethod(
            Invocation.getter(#icyMetadataStream),
            returnValue: _i10.Stream<_i8.IcyMetadata?>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.IcyMetadata?>.empty(),
          )
          as _i10.Stream<_i8.IcyMetadata?>);

  @override
  _i8.PlayerState get playerState =>
      (super.noSuchMethod(
            Invocation.getter(#playerState),
            returnValue: _FakePlayerState_9(
              this,
              Invocation.getter(#playerState),
            ),
            returnValueForMissingStub: _FakePlayerState_9(
              this,
              Invocation.getter(#playerState),
            ),
          )
          as _i8.PlayerState);

  @override
  _i10.Stream<_i8.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i10.Stream<_i8.PlayerState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.PlayerState>.empty(),
          )
          as _i10.Stream<_i8.PlayerState>);

  @override
  List<_i8.IndexedAudioSource> get sequence =>
      (super.noSuchMethod(
            Invocation.getter(#sequence),
            returnValue: <_i8.IndexedAudioSource>[],
            returnValueForMissingStub: <_i8.IndexedAudioSource>[],
          )
          as List<_i8.IndexedAudioSource>);

  @override
  _i10.Stream<List<_i8.IndexedAudioSource>> get sequenceStream =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceStream),
            returnValue: _i10.Stream<List<_i8.IndexedAudioSource>>.empty(),
            returnValueForMissingStub:
                _i10.Stream<List<_i8.IndexedAudioSource>>.empty(),
          )
          as _i10.Stream<List<_i8.IndexedAudioSource>>);

  @override
  List<int> get shuffleIndices =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleIndices),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);

  @override
  _i10.Stream<List<int>> get shuffleIndicesStream =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleIndicesStream),
            returnValue: _i10.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i10.Stream<List<int>>.empty(),
          )
          as _i10.Stream<List<int>>);

  @override
  _i10.Stream<int?> get currentIndexStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexStream),
            returnValue: _i10.Stream<int?>.empty(),
            returnValueForMissingStub: _i10.Stream<int?>.empty(),
          )
          as _i10.Stream<int?>);

  @override
  _i8.SequenceState get sequenceState =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceState),
            returnValue: _FakeSequenceState_10(
              this,
              Invocation.getter(#sequenceState),
            ),
            returnValueForMissingStub: _FakeSequenceState_10(
              this,
              Invocation.getter(#sequenceState),
            ),
          )
          as _i8.SequenceState);

  @override
  _i10.Stream<_i8.SequenceState> get sequenceStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceStateStream),
            returnValue: _i10.Stream<_i8.SequenceState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.SequenceState>.empty(),
          )
          as _i10.Stream<_i8.SequenceState>);

  @override
  bool get hasNext =>
      (super.noSuchMethod(
            Invocation.getter(#hasNext),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasPrevious =>
      (super.noSuchMethod(
            Invocation.getter(#hasPrevious),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<int> get effectiveIndices =>
      (super.noSuchMethod(
            Invocation.getter(#effectiveIndices),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);

  @override
  _i8.LoopMode get loopMode =>
      (super.noSuchMethod(
            Invocation.getter(#loopMode),
            returnValue: _i8.LoopMode.off,
            returnValueForMissingStub: _i8.LoopMode.off,
          )
          as _i8.LoopMode);

  @override
  _i10.Stream<_i8.LoopMode> get loopModeStream =>
      (super.noSuchMethod(
            Invocation.getter(#loopModeStream),
            returnValue: _i10.Stream<_i8.LoopMode>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.LoopMode>.empty(),
          )
          as _i10.Stream<_i8.LoopMode>);

  @override
  bool get shuffleModeEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleModeEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Stream<bool> get shuffleModeEnabledStream =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleModeEnabledStream),
            returnValue: _i10.Stream<bool>.empty(),
            returnValueForMissingStub: _i10.Stream<bool>.empty(),
          )
          as _i10.Stream<bool>);

  @override
  _i10.Stream<int?> get androidAudioSessionIdStream =>
      (super.noSuchMethod(
            Invocation.getter(#androidAudioSessionIdStream),
            returnValue: _i10.Stream<int?>.empty(),
            returnValueForMissingStub: _i10.Stream<int?>.empty(),
          )
          as _i10.Stream<int?>);

  @override
  _i10.Stream<_i8.PlayerException> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i10.Stream<_i8.PlayerException>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.PlayerException>.empty(),
          )
          as _i10.Stream<_i8.PlayerException>);

  @override
  _i10.Stream<_i8.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionDiscontinuityStream),
            returnValue: _i10.Stream<_i8.PositionDiscontinuity>.empty(),
            returnValueForMissingStub:
                _i10.Stream<_i8.PositionDiscontinuity>.empty(),
          )
          as _i10.Stream<_i8.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling =>
      (super.noSuchMethod(
            Invocation.getter(#automaticallyWaitsToMinimizeStalling),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
            Invocation.getter(
              #canUseNetworkResourcesForLiveStreamingWhilePaused,
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get preferredPeakBitRate =>
      (super.noSuchMethod(
            Invocation.getter(#preferredPeakBitRate),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get allowsExternalPlayback =>
      (super.noSuchMethod(
            Invocation.getter(#allowsExternalPlayback),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get webSinkId =>
      (super.noSuchMethod(
            Invocation.getter(#webSinkId),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#webSinkId),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#webSinkId),
            ),
          )
          as String);

  @override
  Duration get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeDuration_8(this, Invocation.getter(#position)),
            returnValueForMissingStub: _FakeDuration_8(
              this,
              Invocation.getter(#position),
            ),
          )
          as Duration);

  @override
  _i10.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i10.Stream<Duration>.empty(),
            returnValueForMissingStub: _i10.Stream<Duration>.empty(),
          )
          as _i10.Stream<Duration>);

  @override
  List<_i8.AudioSource> get audioSources =>
      (super.noSuchMethod(
            Invocation.getter(#audioSources),
            returnValue: <_i8.AudioSource>[],
            returnValueForMissingStub: <_i8.AudioSource>[],
          )
          as List<_i8.AudioSource>);

  @override
  _i10.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPositionStream, [], {
              #steps: steps,
              #minPeriod: minPeriod,
              #maxPeriod: maxPeriod,
            }),
            returnValue: _i10.Stream<Duration>.empty(),
            returnValueForMissingStub: _i10.Stream<Duration>.empty(),
          )
          as _i10.Stream<Duration>);

  @override
  _i10.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setUrl,
              [url],
              {
                #headers: headers,
                #initialPosition: initialPosition,
                #preload: preload,
                #tag: tag,
              },
            ),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setFilePath,
              [filePath],
              {#initialPosition: initialPosition, #preload: preload, #tag: tag},
            ),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAsset,
              [assetPath],
              {
                #package: package,
                #preload: preload,
                #initialPosition: initialPosition,
                #tag: tag,
              },
            ),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<Duration?> setAudioSource(
    _i8.AudioSource? audioSource, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAudioSource,
              [audioSource],
              {
                #preload: preload,
                #initialIndex: initialIndex,
                #initialPosition: initialPosition,
              },
            ),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<Duration?> setAudioSources(
    List<_i8.AudioSource>? audioSources, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
    _i8.ShuffleOrder? shuffleOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAudioSources,
              [audioSources],
              {
                #preload: preload,
                #initialIndex: initialIndex,
                #initialPosition: initialPosition,
                #shuffleOrder: shuffleOrder,
              },
            ),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<Duration?> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<void> addAudioSource(_i8.AudioSource? audioSource) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioSource, [audioSource]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> insertAudioSource(
    int? index,
    _i8.AudioSource? audioSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAudioSource, [index, audioSource]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> addAudioSources(List<_i8.AudioSource>? audioSources) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioSources, [audioSources]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> insertAudioSources(
    int? index,
    List<_i8.AudioSource>? audioSources,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAudioSources, [index, audioSources]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeAudioSourceAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeAudioSourceAt, [index]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeAudioSourceRange(int? start, int? end) =>
      (super.noSuchMethod(
            Invocation.method(#removeAudioSourceRange, [start, end]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> moveAudioSource(int? currentIndex, int? newIndex) =>
      (super.noSuchMethod(
            Invocation.method(#moveAudioSource, [currentIndex, newIndex]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearAudioSources() =>
      (super.noSuchMethod(
            Invocation.method(#clearAudioSources, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setClip, [], {
              #start: start,
              #end: end,
              #tag: tag,
            }),
            returnValue: _i10.Future<Duration?>.value(),
            returnValueForMissingStub: _i10.Future<Duration?>.value(),
          )
          as _i10.Future<Duration?>);

  @override
  _i10.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setSkipSilenceEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setSkipSilenceEnabled, [enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setLoopMode(_i8.LoopMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setLoopMode, [mode]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setShuffleModeEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleModeEnabled, [enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> shuffle() =>
      (super.noSuchMethod(
            Invocation.method(#shuffle, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setAutomaticallyWaitsToMinimizeStalling(
    bool? automaticallyWaitsToMinimizeStalling,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAutomaticallyWaitsToMinimizeStalling, [
              automaticallyWaitsToMinimizeStalling,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
    bool? canUseNetworkResourcesForLiveStreamingWhilePaused,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
              [canUseNetworkResourcesForLiveStreamingWhilePaused],
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredPeakBitRate, [preferredPeakBitRate]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
            Invocation.method(#setAllowsExternalPlayback, [
              allowsExternalPlayback,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> seek(Duration? position, {int? index}) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position], {#index: index}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> seekToNext() =>
      (super.noSuchMethod(
            Invocation.method(#seekToNext, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> seekToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#seekToPrevious, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setAndroidAudioAttributes(
    _i21.AndroidAudioAttributes? audioAttributes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAndroidAudioAttributes, [audioAttributes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setWebCrossOrigin(_i8.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
            Invocation.method(#setWebCrossOrigin, [webCrossOrigin]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setWebSinkId(String? webSinkId) =>
      (super.noSuchMethod(
            Invocation.method(#setWebSinkId, [webSinkId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
