// Mocks generated by Mockito 5.4.6 from annotations
// in music_player_frontend/test/core/services/app_audio_service_playback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i20;
import 'dart:typed_data' as _i16;

import 'package:audio_session/audio_session.dart' as _i21;
import 'package:flutter/cupertino.dart' as _i4;
import 'package:http/http.dart' as _i10;
import 'package:just_audio/just_audio.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:music_player_frontend/core/dtos/playback_state_dto.dart'
    as _i19;
import 'package:music_player_frontend/core/dtos/playlist_page_dto.dart' as _i8;
import 'package:music_player_frontend/core/dtos/song_page_dto.dart' as _i3;
import 'package:music_player_frontend/core/entities/app_settings.dart' as _i6;
import 'package:music_player_frontend/core/entities/audio_settings.dart' as _i5;
import 'package:music_player_frontend/core/entities/playlist.dart' as _i7;
import 'package:music_player_frontend/core/entities/song.dart' as _i2;
import 'package:music_player_frontend/core/services/playlist_service.dart'
    as _i15;
import 'package:music_player_frontend/core/services/rest_clients/auth_service.dart'
    as _i9;
import 'package:music_player_frontend/core/services/rest_clients/playback_rest_service.dart'
    as _i18;
import 'package:music_player_frontend/core/services/settings_service.dart'
    as _i14;
import 'package:music_player_frontend/core/services/song_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSong_0 extends _i1.SmartFake implements _i2.Song {
  _FakeSong_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSongPageDto_1 extends _i1.SmartFake implements _i3.SongPageDto {
  _FakeSongPageDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeAudioSettings_3 extends _i1.SmartFake implements _i5.AudioSettings {
  _FakeAudioSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_4 extends _i1.SmartFake implements _i6.AppSettings {
  _FakeAppSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylist_5 extends _i1.SmartFake implements _i7.Playlist {
  _FakePlaylist_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistPageDto_6 extends _i1.SmartFake
    implements _i8.PlaylistPageDto {
  _FakePlaylistPageDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_7 extends _i1.SmartFake implements _i9.AuthService {
  _FakeAuthService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_8 extends _i1.SmartFake implements _i10.Response {
  _FakeResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerEvent_9 extends _i1.SmartFake implements _i11.PlayerEvent {
  _FakePlayerEvent_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackEvent_10 extends _i1.SmartFake
    implements _i11.PlaybackEvent {
  _FakePlaybackEvent_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerState_12 extends _i1.SmartFake implements _i11.PlayerState {
  _FakePlayerState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSequenceState_13 extends _i1.SmartFake
    implements _i11.SequenceState {
  _FakeSequenceState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SongService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongService extends _i1.Mock implements _i12.SongService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i13.Stream<dynamic> get watchSongs =>
      (super.noSuchMethod(
            Invocation.getter(#watchSongs),
            returnValue: _i13.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i13.Stream<dynamic>.empty(),
          )
          as _i13.Stream<dynamic>);

  @override
  _i2.Song addSongEntity(_i2.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#addSongEntity, [song]),
            returnValue: _FakeSong_0(
              this,
              Invocation.method(#addSongEntity, [song]),
            ),
            returnValueForMissingStub: _FakeSong_0(
              this,
              Invocation.method(#addSongEntity, [song]),
            ),
          )
          as _i2.Song);

  @override
  int getSongCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSongCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i2.Song> addSongsEntitiesBatch(List<_i2.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#addSongsEntitiesBatch, [songs]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  void addSongsBatch(List<_i2.Song>? songs) => super.noSuchMethod(
    Invocation.method(#addSongsBatch, [songs]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Song? getSongContaining(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSongContaining, [query]),
            returnValueForMissingStub: null,
          )
          as _i2.Song?);

  @override
  _i13.Future<List<_i2.Song>> getAllSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSongs, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<List<_i2.Song>> getSongs(
    String? query,
    String? sortField,
    bool? ascending,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSongs, [query, sortField, ascending]),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<_i2.Song?> getSong(
    String? songPath, {
    bool? preferServer = false,
    int? serverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSong,
              [songPath],
              {#preferServer: preferServer, #serverId: serverId},
            ),
            returnValue: _i13.Future<_i2.Song?>.value(),
            returnValueForMissingStub: _i13.Future<_i2.Song?>.value(),
          )
          as _i13.Future<_i2.Song?>);

  @override
  _i13.Future<List<_i2.Song>> refreshServerSongs() =>
      (super.noSuchMethod(
            Invocation.method(#refreshServerSongs, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<List<_i2.Song>> getServerSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getServerSongs, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i2.Song? getSongByServerId(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getSongByServerId, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i2.Song?);

  @override
  _i13.Future<_i2.Song?> fetchSongByServerId(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSongByServerId, [serverId]),
            returnValue: _i13.Future<_i2.Song?>.value(),
            returnValueForMissingStub: _i13.Future<_i2.Song?>.value(),
          )
          as _i13.Future<_i2.Song?>);

  @override
  void updateSong(_i2.Song? song) => super.noSuchMethod(
    Invocation.method(#updateSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSongsBatch(List<_i2.Song>? songs) => super.noSuchMethod(
    Invocation.method(#updateSongsBatch, [songs]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteSong(_i2.Song? song) => super.noSuchMethod(
    Invocation.method(#deleteSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<List<_i2.Song>> getSongsFromPaths(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsFromPaths, [paths]),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  void linkToServerId(int? localId, int? serverId) => super.noSuchMethod(
    Invocation.method(#linkToServerId, [localId, serverId]),
    returnValueForMissingStub: null,
  );

  @override
  void recordPlay(int? songId) => super.noSuchMethod(
    Invocation.method(#recordPlay, [songId]),
    returnValueForMissingStub: null,
  );

  @override
  void runSync() => super.noSuchMethod(
    Invocation.method(#runSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i3.SongPageDto> getSongsPage(
    String? query,
    String? sortField,
    bool? ascending,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsPage, [
              query,
              sortField,
              ascending,
              page,
              pageSize,
            ]),
            returnValue: _i13.Future<_i3.SongPageDto>.value(
              _FakeSongPageDto_1(
                this,
                Invocation.method(#getSongsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  pageSize,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i3.SongPageDto>.value(
              _FakeSongPageDto_1(
                this,
                Invocation.method(#getSongsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  pageSize,
                ]),
              ),
            ),
          )
          as _i13.Future<_i3.SongPageDto>);

  @override
  List<_i2.Song> getSongsPagedLocal(
    String? query,
    String? sortField,
    bool? ascending,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsPagedLocal, [
              query,
              sortField,
              ascending,
              page,
              pageSize,
            ]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  _i13.Future<List<_i2.Song>> searchSongsFromServer(
    String? query, {
    int? page = 0,
    int? size = 50,
    String? sort = 'name,asc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchSongsFromServer,
              [query],
              {#page: page, #size: size, #sort: sort},
            ),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<_i3.SongPageDto> searchSongsPageFromServer(
    String? query, {
    int? page = 0,
    int? size = 50,
    String? sort = 'name,asc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchSongsPageFromServer,
              [query],
              {#page: page, #size: size, #sort: sort},
            ),
            returnValue: _i13.Future<_i3.SongPageDto>.value(
              _FakeSongPageDto_1(
                this,
                Invocation.method(
                  #searchSongsPageFromServer,
                  [query],
                  {#page: page, #size: size, #sort: sort},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i3.SongPageDto>.value(
              _FakeSongPageDto_1(
                this,
                Invocation.method(
                  #searchSongsPageFromServer,
                  [query],
                  {#page: page, #size: size, #sort: sort},
                ),
              ),
            ),
          )
          as _i13.Future<_i3.SongPageDto>);

  @override
  _i13.Future<List<_i2.Song>> getRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<List<_i2.Song>> getForgottenFavourites() =>
      (super.noSuchMethod(
            Invocation.method(#getForgottenFavourites, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i13.Future<List<_i2.Song>> getQuickDial() =>
      (super.noSuchMethod(
            Invocation.method(#getQuickDial, []),
            returnValue: _i13.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i13.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i13.Future<List<_i2.Song>>);

  @override
  _i4.Widget getCoverArt(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getCoverArt, [serverId]),
            returnValue: _FakeWidget_2(
              this,
              Invocation.method(#getCoverArt, [serverId]),
            ),
            returnValueForMissingStub: _FakeWidget_2(
              this,
              Invocation.method(#getCoverArt, [serverId]),
            ),
          )
          as _i4.Widget);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i14.SettingsService {
  @override
  _i5.AudioSettings getAudioSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioSettings, []),
            returnValue: _FakeAudioSettings_3(
              this,
              Invocation.method(#getAudioSettings, []),
            ),
            returnValueForMissingStub: _FakeAudioSettings_3(
              this,
              Invocation.method(#getAudioSettings, []),
            ),
          )
          as _i5.AudioSettings);

  @override
  _i6.AppSettings getAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAppSettings, []),
            returnValue: _FakeAppSettings_4(
              this,
              Invocation.method(#getAppSettings, []),
            ),
            returnValueForMissingStub: _FakeAppSettings_4(
              this,
              Invocation.method(#getAppSettings, []),
            ),
          )
          as _i6.AppSettings);

  @override
  void updateAudioSettings(_i5.AudioSettings? newSettings) =>
      super.noSuchMethod(
        Invocation.method(#updateAudioSettings, [newSettings]),
        returnValueForMissingStub: null,
      );

  @override
  void updateAppSettings(_i6.AppSettings? newSettings) => super.noSuchMethod(
    Invocation.method(#updateAppSettings, [newSettings]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PlaylistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistService extends _i1.Mock implements _i15.PlaylistService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i13.Stream<dynamic> watchPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#watchPlaylists, []),
            returnValue: _i13.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i13.Stream<dynamic>.empty(),
          )
          as _i13.Stream<dynamic>);

  @override
  _i13.Future<_i7.Playlist> addPlaylist(
    String? name,
    List<_i2.Song>? songs,
    String? whereToAdd,
    _i16.Uint8List? coverArt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPlaylist, [
              name,
              songs,
              whereToAdd,
              coverArt,
            ]),
            returnValue: _i13.Future<_i7.Playlist>.value(
              _FakePlaylist_5(
                this,
                Invocation.method(#addPlaylist, [
                  name,
                  songs,
                  whereToAdd,
                  coverArt,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.Playlist>.value(
              _FakePlaylist_5(
                this,
                Invocation.method(#addPlaylist, [
                  name,
                  songs,
                  whereToAdd,
                  coverArt,
                ]),
              ),
            ),
          )
          as _i13.Future<_i7.Playlist>);

  @override
  _i13.Future<_i7.Playlist> updatePlaylist(_i7.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlist]),
            returnValue: _i13.Future<_i7.Playlist>.value(
              _FakePlaylist_5(
                this,
                Invocation.method(#updatePlaylist, [playlist]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.Playlist>.value(
              _FakePlaylist_5(
                this,
                Invocation.method(#updatePlaylist, [playlist]),
              ),
            ),
          )
          as _i13.Future<_i7.Playlist>);

  @override
  _i7.Playlist? getPlaylist(int? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [playlistId]),
            returnValueForMissingStub: null,
          )
          as _i7.Playlist?);

  @override
  void initializeIndestructible() => super.noSuchMethod(
    Invocation.method(#initializeIndestructible, []),
    returnValueForMissingStub: null,
  );

  @override
  void initializeQueue() => super.noSuchMethod(
    Invocation.method(#initializeQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Playlist getQueuePlaylist() =>
      (super.noSuchMethod(
            Invocation.method(#getQueuePlaylist, []),
            returnValue: _FakePlaylist_5(
              this,
              Invocation.method(#getQueuePlaylist, []),
            ),
            returnValueForMissingStub: _FakePlaylist_5(
              this,
              Invocation.method(#getQueuePlaylist, []),
            ),
          )
          as _i7.Playlist);

  @override
  void initializeFavorites() => super.noSuchMethod(
    Invocation.method(#initializeFavorites, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Playlist getFavoritesPlaylist() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoritesPlaylist, []),
            returnValue: _FakePlaylist_5(
              this,
              Invocation.method(#getFavoritesPlaylist, []),
            ),
            returnValueForMissingStub: _FakePlaylist_5(
              this,
              Invocation.method(#getFavoritesPlaylist, []),
            ),
          )
          as _i7.Playlist);

  @override
  void initializeMostPlayed() => super.noSuchMethod(
    Invocation.method(#initializeMostPlayed, []),
    returnValueForMissingStub: null,
  );

  @override
  void initializeRecentlyPlayed() => super.noSuchMethod(
    Invocation.method(#initializeRecentlyPlayed, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateMostPlayedPlaylist() => super.noSuchMethod(
    Invocation.method(#updateMostPlayedPlaylist, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateRecentlyPlayedPlaylist() => super.noSuchMethod(
    Invocation.method(#updateRecentlyPlayedPlaylist, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateFavoritesPlaylist() => super.noSuchMethod(
    Invocation.method(#updateFavoritesPlaylist, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i7.Playlist> getIndestructiblePlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getIndestructiblePlaylists, []),
            returnValue: <_i7.Playlist>[],
            returnValueForMissingStub: <_i7.Playlist>[],
          )
          as List<_i7.Playlist>);

  @override
  List<_i7.Playlist> getNormalPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getNormalPlaylists, []),
            returnValue: <_i7.Playlist>[],
            returnValueForMissingStub: <_i7.Playlist>[],
          )
          as List<_i7.Playlist>);

  @override
  List<_i7.Playlist> getPlaylists(
    String? query,
    String? sortField,
    bool? flag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylists, [query, sortField, flag]),
            returnValue: <_i7.Playlist>[],
            returnValueForMissingStub: <_i7.Playlist>[],
          )
          as List<_i7.Playlist>);

  @override
  _i13.Future<_i8.PlaylistPageDto> getPlaylistsPage(
    String? query,
    String? sortField,
    bool? ascending,
    int? page,
    int? size,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistsPage, [
              query,
              sortField,
              ascending,
              page,
              size,
            ]),
            returnValue: _i13.Future<_i8.PlaylistPageDto>.value(
              _FakePlaylistPageDto_6(
                this,
                Invocation.method(#getPlaylistsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.PlaylistPageDto>.value(
              _FakePlaylistPageDto_6(
                this,
                Invocation.method(#getPlaylistsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
          )
          as _i13.Future<_i8.PlaylistPageDto>);

  @override
  _i7.Playlist cacheServerPlaylist(_i7.Playlist? serverPlaylist) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            returnValue: _FakePlaylist_5(
              this,
              Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            ),
            returnValueForMissingStub: _FakePlaylist_5(
              this,
              Invocation.method(#cacheServerPlaylist, [serverPlaylist]),
            ),
          )
          as _i7.Playlist);

  @override
  List<_i7.Playlist> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue: <_i7.Playlist>[],
            returnValueForMissingStub: <_i7.Playlist>[],
          )
          as List<_i7.Playlist>);

  @override
  void addToPlaylist(_i7.Playlist? playlist, List<_i2.Song>? songs) =>
      super.noSuchMethod(
        Invocation.method(#addToPlaylist, [playlist, songs]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteFromPlaylist(_i2.Song? song, _i7.Playlist? playlist) =>
      super.noSuchMethod(
        Invocation.method(#deleteFromPlaylist, [song, playlist]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteAllSongsFromPlaylist(_i7.Playlist? playlist) => super.noSuchMethod(
    Invocation.method(#deleteAllSongsFromPlaylist, [playlist]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> deletePlaylist(_i7.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlist]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Future<String?> get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _i13.Future<String?>.value(),
            returnValueForMissingStub: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  void startTokenRefresh() => super.noSuchMethod(
    Invocation.method(#startTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopTokenRefresh() => super.noSuchMethod(
    Invocation.method(#stopTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> saveTokens(String? access, String? refresh) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [access, refresh]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> sendLoginCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendLoginCode, [email]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> verifyCode(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [email, code]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<String?> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i13.Future<String?>.value(),
            returnValueForMissingStub: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<bool> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [PlaybackRestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackRestService extends _i1.Mock
    implements _i18.PlaybackRestService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i9.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_7(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_7(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i9.AuthService);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set authService(_i9.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i19.PlaybackStateDto?> getPlaybackState() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackState, []),
            returnValue: _i13.Future<_i19.PlaybackStateDto?>.value(),
            returnValueForMissingStub:
                _i13.Future<_i19.PlaybackStateDto?>.value(),
          )
          as _i13.Future<_i19.PlaybackStateDto?>);

  @override
  _i13.Future<void> savePlaybackState(_i19.PlaybackStateDto? state) =>
      (super.noSuchMethod(
            Invocation.method(#savePlaybackState, [state]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i10.Response> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#post, [endpoint, body])),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#post, [endpoint, body])),
            ),
          )
          as _i13.Future<_i10.Response>);

  @override
  _i13.Future<_i10.Response> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#get, [endpoint])),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#get, [endpoint])),
            ),
          )
          as _i13.Future<_i10.Response>);

  @override
  _i13.Future<_i10.Response> put(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#put, [endpoint, body])),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#put, [endpoint, body])),
            ),
          )
          as _i13.Future<_i10.Response>);

  @override
  _i13.Future<_i10.Response> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#delete, [endpoint])),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(this, Invocation.method(#delete, [endpoint])),
            ),
          )
          as _i13.Future<_i10.Response>);

  @override
  _i13.Future<_i10.Response> multipartRequest(
    String? method,
    String? endpoint, {
    Map<String, String>? fields,
    List<_i10.MultipartFile>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [method, endpoint],
              {#fields: fields, #files: files},
            ),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
          )
          as _i13.Future<_i10.Response>);

  @override
  _i13.Future<_i10.Response> multipartRequestWithProgress(
    String? method,
    String? endpoint,
    _i20.File? file,
    Map<String, String>? fields,
    void Function(int, int)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#multipartRequestWithProgress, [
              method,
              endpoint,
              file,
              fields,
              onProgress,
            ]),
            returnValue: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i10.Response>.value(
              _FakeResponse_8(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i13.Future<_i10.Response>);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i11.AudioPlayer {
  @override
  _i11.PlayerEvent get playerEvent =>
      (super.noSuchMethod(
            Invocation.getter(#playerEvent),
            returnValue: _FakePlayerEvent_9(
              this,
              Invocation.getter(#playerEvent),
            ),
            returnValueForMissingStub: _FakePlayerEvent_9(
              this,
              Invocation.getter(#playerEvent),
            ),
          )
          as _i11.PlayerEvent);

  @override
  _i13.Stream<_i11.PlayerEvent> get playerEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerEventStream),
            returnValue: _i13.Stream<_i11.PlayerEvent>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.PlayerEvent>.empty(),
          )
          as _i13.Stream<_i11.PlayerEvent>);

  @override
  _i11.PlaybackEvent get playbackEvent =>
      (super.noSuchMethod(
            Invocation.getter(#playbackEvent),
            returnValue: _FakePlaybackEvent_10(
              this,
              Invocation.getter(#playbackEvent),
            ),
            returnValueForMissingStub: _FakePlaybackEvent_10(
              this,
              Invocation.getter(#playbackEvent),
            ),
          )
          as _i11.PlaybackEvent);

  @override
  _i13.Stream<_i11.PlaybackEvent> get playbackEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackEventStream),
            returnValue: _i13.Stream<_i11.PlaybackEvent>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.PlaybackEvent>.empty(),
          )
          as _i13.Stream<_i11.PlaybackEvent>);

  @override
  _i13.Stream<Duration?> get durationStream =>
      (super.noSuchMethod(
            Invocation.getter(#durationStream),
            returnValue: _i13.Stream<Duration?>.empty(),
            returnValueForMissingStub: _i13.Stream<Duration?>.empty(),
          )
          as _i13.Stream<Duration?>);

  @override
  _i11.ProcessingState get processingState =>
      (super.noSuchMethod(
            Invocation.getter(#processingState),
            returnValue: _i11.ProcessingState.idle,
            returnValueForMissingStub: _i11.ProcessingState.idle,
          )
          as _i11.ProcessingState);

  @override
  _i13.Stream<_i11.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#processingStateStream),
            returnValue: _i13.Stream<_i11.ProcessingState>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i11.ProcessingState>.empty(),
          )
          as _i13.Stream<_i11.ProcessingState>);

  @override
  bool get playing =>
      (super.noSuchMethod(
            Invocation.getter(#playing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Stream<bool> get playingStream =>
      (super.noSuchMethod(
            Invocation.getter(#playingStream),
            returnValue: _i13.Stream<bool>.empty(),
            returnValueForMissingStub: _i13.Stream<bool>.empty(),
          )
          as _i13.Stream<bool>);

  @override
  double get volume =>
      (super.noSuchMethod(
            Invocation.getter(#volume),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i13.Stream<double> get volumeStream =>
      (super.noSuchMethod(
            Invocation.getter(#volumeStream),
            returnValue: _i13.Stream<double>.empty(),
            returnValueForMissingStub: _i13.Stream<double>.empty(),
          )
          as _i13.Stream<double>);

  @override
  double get speed =>
      (super.noSuchMethod(
            Invocation.getter(#speed),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i13.Stream<double> get speedStream =>
      (super.noSuchMethod(
            Invocation.getter(#speedStream),
            returnValue: _i13.Stream<double>.empty(),
            returnValueForMissingStub: _i13.Stream<double>.empty(),
          )
          as _i13.Stream<double>);

  @override
  double get pitch =>
      (super.noSuchMethod(
            Invocation.getter(#pitch),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i13.Stream<double> get pitchStream =>
      (super.noSuchMethod(
            Invocation.getter(#pitchStream),
            returnValue: _i13.Stream<double>.empty(),
            returnValueForMissingStub: _i13.Stream<double>.empty(),
          )
          as _i13.Stream<double>);

  @override
  bool get skipSilenceEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#skipSilenceEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Stream<bool> get skipSilenceEnabledStream =>
      (super.noSuchMethod(
            Invocation.getter(#skipSilenceEnabledStream),
            returnValue: _i13.Stream<bool>.empty(),
            returnValueForMissingStub: _i13.Stream<bool>.empty(),
          )
          as _i13.Stream<bool>);

  @override
  Duration get bufferedPosition =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPosition),
            returnValue: _FakeDuration_11(
              this,
              Invocation.getter(#bufferedPosition),
            ),
            returnValueForMissingStub: _FakeDuration_11(
              this,
              Invocation.getter(#bufferedPosition),
            ),
          )
          as Duration);

  @override
  _i13.Stream<Duration> get bufferedPositionStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionStream),
            returnValue: _i13.Stream<Duration>.empty(),
            returnValueForMissingStub: _i13.Stream<Duration>.empty(),
          )
          as _i13.Stream<Duration>);

  @override
  _i13.Stream<_i11.IcyMetadata?> get icyMetadataStream =>
      (super.noSuchMethod(
            Invocation.getter(#icyMetadataStream),
            returnValue: _i13.Stream<_i11.IcyMetadata?>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.IcyMetadata?>.empty(),
          )
          as _i13.Stream<_i11.IcyMetadata?>);

  @override
  _i11.PlayerState get playerState =>
      (super.noSuchMethod(
            Invocation.getter(#playerState),
            returnValue: _FakePlayerState_12(
              this,
              Invocation.getter(#playerState),
            ),
            returnValueForMissingStub: _FakePlayerState_12(
              this,
              Invocation.getter(#playerState),
            ),
          )
          as _i11.PlayerState);

  @override
  _i13.Stream<_i11.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i13.Stream<_i11.PlayerState>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.PlayerState>.empty(),
          )
          as _i13.Stream<_i11.PlayerState>);

  @override
  List<_i11.IndexedAudioSource> get sequence =>
      (super.noSuchMethod(
            Invocation.getter(#sequence),
            returnValue: <_i11.IndexedAudioSource>[],
            returnValueForMissingStub: <_i11.IndexedAudioSource>[],
          )
          as List<_i11.IndexedAudioSource>);

  @override
  _i13.Stream<List<_i11.IndexedAudioSource>> get sequenceStream =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceStream),
            returnValue: _i13.Stream<List<_i11.IndexedAudioSource>>.empty(),
            returnValueForMissingStub:
                _i13.Stream<List<_i11.IndexedAudioSource>>.empty(),
          )
          as _i13.Stream<List<_i11.IndexedAudioSource>>);

  @override
  List<int> get shuffleIndices =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleIndices),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);

  @override
  _i13.Stream<List<int>> get shuffleIndicesStream =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleIndicesStream),
            returnValue: _i13.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i13.Stream<List<int>>.empty(),
          )
          as _i13.Stream<List<int>>);

  @override
  _i13.Stream<int?> get currentIndexStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexStream),
            returnValue: _i13.Stream<int?>.empty(),
            returnValueForMissingStub: _i13.Stream<int?>.empty(),
          )
          as _i13.Stream<int?>);

  @override
  _i11.SequenceState get sequenceState =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceState),
            returnValue: _FakeSequenceState_13(
              this,
              Invocation.getter(#sequenceState),
            ),
            returnValueForMissingStub: _FakeSequenceState_13(
              this,
              Invocation.getter(#sequenceState),
            ),
          )
          as _i11.SequenceState);

  @override
  _i13.Stream<_i11.SequenceState> get sequenceStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceStateStream),
            returnValue: _i13.Stream<_i11.SequenceState>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.SequenceState>.empty(),
          )
          as _i13.Stream<_i11.SequenceState>);

  @override
  bool get hasNext =>
      (super.noSuchMethod(
            Invocation.getter(#hasNext),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasPrevious =>
      (super.noSuchMethod(
            Invocation.getter(#hasPrevious),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<int> get effectiveIndices =>
      (super.noSuchMethod(
            Invocation.getter(#effectiveIndices),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);

  @override
  _i11.LoopMode get loopMode =>
      (super.noSuchMethod(
            Invocation.getter(#loopMode),
            returnValue: _i11.LoopMode.off,
            returnValueForMissingStub: _i11.LoopMode.off,
          )
          as _i11.LoopMode);

  @override
  _i13.Stream<_i11.LoopMode> get loopModeStream =>
      (super.noSuchMethod(
            Invocation.getter(#loopModeStream),
            returnValue: _i13.Stream<_i11.LoopMode>.empty(),
            returnValueForMissingStub: _i13.Stream<_i11.LoopMode>.empty(),
          )
          as _i13.Stream<_i11.LoopMode>);

  @override
  bool get shuffleModeEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleModeEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Stream<bool> get shuffleModeEnabledStream =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleModeEnabledStream),
            returnValue: _i13.Stream<bool>.empty(),
            returnValueForMissingStub: _i13.Stream<bool>.empty(),
          )
          as _i13.Stream<bool>);

  @override
  _i13.Stream<int?> get androidAudioSessionIdStream =>
      (super.noSuchMethod(
            Invocation.getter(#androidAudioSessionIdStream),
            returnValue: _i13.Stream<int?>.empty(),
            returnValueForMissingStub: _i13.Stream<int?>.empty(),
          )
          as _i13.Stream<int?>);

  @override
  _i13.Stream<_i11.PlayerException> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i13.Stream<_i11.PlayerException>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i11.PlayerException>.empty(),
          )
          as _i13.Stream<_i11.PlayerException>);

  @override
  _i13.Stream<_i11.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionDiscontinuityStream),
            returnValue: _i13.Stream<_i11.PositionDiscontinuity>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i11.PositionDiscontinuity>.empty(),
          )
          as _i13.Stream<_i11.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling =>
      (super.noSuchMethod(
            Invocation.getter(#automaticallyWaitsToMinimizeStalling),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
            Invocation.getter(
              #canUseNetworkResourcesForLiveStreamingWhilePaused,
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get preferredPeakBitRate =>
      (super.noSuchMethod(
            Invocation.getter(#preferredPeakBitRate),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get allowsExternalPlayback =>
      (super.noSuchMethod(
            Invocation.getter(#allowsExternalPlayback),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get webSinkId =>
      (super.noSuchMethod(
            Invocation.getter(#webSinkId),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#webSinkId),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#webSinkId),
            ),
          )
          as String);

  @override
  Duration get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeDuration_11(this, Invocation.getter(#position)),
            returnValueForMissingStub: _FakeDuration_11(
              this,
              Invocation.getter(#position),
            ),
          )
          as Duration);

  @override
  _i13.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i13.Stream<Duration>.empty(),
            returnValueForMissingStub: _i13.Stream<Duration>.empty(),
          )
          as _i13.Stream<Duration>);

  @override
  List<_i11.AudioSource> get audioSources =>
      (super.noSuchMethod(
            Invocation.getter(#audioSources),
            returnValue: <_i11.AudioSource>[],
            returnValueForMissingStub: <_i11.AudioSource>[],
          )
          as List<_i11.AudioSource>);

  @override
  _i13.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPositionStream, [], {
              #steps: steps,
              #minPeriod: minPeriod,
              #maxPeriod: maxPeriod,
            }),
            returnValue: _i13.Stream<Duration>.empty(),
            returnValueForMissingStub: _i13.Stream<Duration>.empty(),
          )
          as _i13.Stream<Duration>);

  @override
  _i13.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setUrl,
              [url],
              {
                #headers: headers,
                #initialPosition: initialPosition,
                #preload: preload,
                #tag: tag,
              },
            ),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setFilePath,
              [filePath],
              {#initialPosition: initialPosition, #preload: preload, #tag: tag},
            ),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAsset,
              [assetPath],
              {
                #package: package,
                #preload: preload,
                #initialPosition: initialPosition,
                #tag: tag,
              },
            ),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<Duration?> setAudioSource(
    _i11.AudioSource? audioSource, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAudioSource,
              [audioSource],
              {
                #preload: preload,
                #initialIndex: initialIndex,
                #initialPosition: initialPosition,
              },
            ),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<Duration?> setAudioSources(
    List<_i11.AudioSource>? audioSources, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
    _i11.ShuffleOrder? shuffleOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAudioSources,
              [audioSources],
              {
                #preload: preload,
                #initialIndex: initialIndex,
                #initialPosition: initialPosition,
                #shuffleOrder: shuffleOrder,
              },
            ),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<Duration?> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<void> addAudioSource(_i11.AudioSource? audioSource) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioSource, [audioSource]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> insertAudioSource(
    int? index,
    _i11.AudioSource? audioSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAudioSource, [index, audioSource]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> addAudioSources(List<_i11.AudioSource>? audioSources) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioSources, [audioSources]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> insertAudioSources(
    int? index,
    List<_i11.AudioSource>? audioSources,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAudioSources, [index, audioSources]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> removeAudioSourceAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeAudioSourceAt, [index]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> removeAudioSourceRange(int? start, int? end) =>
      (super.noSuchMethod(
            Invocation.method(#removeAudioSourceRange, [start, end]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> moveAudioSource(int? currentIndex, int? newIndex) =>
      (super.noSuchMethod(
            Invocation.method(#moveAudioSource, [currentIndex, newIndex]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> clearAudioSources() =>
      (super.noSuchMethod(
            Invocation.method(#clearAudioSources, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setClip, [], {
              #start: start,
              #end: end,
              #tag: tag,
            }),
            returnValue: _i13.Future<Duration?>.value(),
            returnValueForMissingStub: _i13.Future<Duration?>.value(),
          )
          as _i13.Future<Duration?>);

  @override
  _i13.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setSkipSilenceEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setSkipSilenceEnabled, [enabled]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setLoopMode(_i11.LoopMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setLoopMode, [mode]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setShuffleModeEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleModeEnabled, [enabled]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> shuffle() =>
      (super.noSuchMethod(
            Invocation.method(#shuffle, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setAutomaticallyWaitsToMinimizeStalling(
    bool? automaticallyWaitsToMinimizeStalling,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAutomaticallyWaitsToMinimizeStalling, [
              automaticallyWaitsToMinimizeStalling,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
    bool? canUseNetworkResourcesForLiveStreamingWhilePaused,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
              [canUseNetworkResourcesForLiveStreamingWhilePaused],
            ),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredPeakBitRate, [preferredPeakBitRate]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
            Invocation.method(#setAllowsExternalPlayback, [
              allowsExternalPlayback,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> seek(Duration? position, {int? index}) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position], {#index: index}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> seekToNext() =>
      (super.noSuchMethod(
            Invocation.method(#seekToNext, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> seekToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#seekToPrevious, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setAndroidAudioAttributes(
    _i21.AndroidAudioAttributes? audioAttributes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAndroidAudioAttributes, [audioAttributes]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setWebCrossOrigin(_i11.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
            Invocation.method(#setWebCrossOrigin, [webCrossOrigin]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setWebSinkId(String? webSinkId) =>
      (super.noSuchMethod(
            Invocation.method(#setWebSinkId, [webSinkId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}
