// Mocks generated by Mockito 5.4.6 from annotations
// in music_player_frontend/test/core/services/song_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i17;
import 'dart:typed_data' as _i16;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:music_player_frontend/core/dtos/album_page_dto.dart' as _i9;
import 'package:music_player_frontend/core/dtos/artist_page_dto.dart' as _i7;
import 'package:music_player_frontend/core/dtos/negotiation_request_dto.dart'
    as _i15;
import 'package:music_player_frontend/core/dtos/negotiation_response_dto.dart'
    as _i14;
import 'package:music_player_frontend/core/dtos/song_page_dto.dart' as _i4;
import 'package:music_player_frontend/core/dtos/song_sync_dto.dart' as _i22;
import 'package:music_player_frontend/core/dtos/sync_response_dto.dart' as _i21;
import 'package:music_player_frontend/core/entities/album.dart' as _i8;
import 'package:music_player_frontend/core/entities/artist.dart' as _i6;
import 'package:music_player_frontend/core/entities/song.dart' as _i2;
import 'package:music_player_frontend/core/repository/interfaces/song_repository.dart'
    as _i10;
import 'package:music_player_frontend/core/services/album_service.dart' as _i19;
import 'package:music_player_frontend/core/services/artist_service.dart'
    as _i18;
import 'package:music_player_frontend/core/services/rest_clients/auth_service.dart'
    as _i3;
import 'package:music_player_frontend/core/services/rest_clients/data_sync_rest_service.dart'
    as _i20;
import 'package:music_player_frontend/core/services/rest_clients/song_rest_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSong_0 extends _i1.SmartFake implements _i2.Song {
  _FakeSong_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSongPageDto_2 extends _i1.SmartFake implements _i4.SongPageDto {
  _FakeSongPageDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArtist_4 extends _i1.SmartFake implements _i6.Artist {
  _FakeArtist_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArtistPageDto_5 extends _i1.SmartFake implements _i7.ArtistPageDto {
  _FakeArtistPageDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlbum_6 extends _i1.SmartFake implements _i8.Album {
  _FakeAlbum_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlbumPageDto_7 extends _i1.SmartFake implements _i9.AlbumPageDto {
  _FakeAlbumPageDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends _i1.Mock implements _i10.SongRepository {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Stream<dynamic> watchSongs() =>
      (super.noSuchMethod(
            Invocation.method(#watchSongs, []),
            returnValue: _i11.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i11.Stream<dynamic>.empty(),
          )
          as _i11.Stream<dynamic>);

  @override
  _i2.Song saveSong(_i2.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#saveSong, [song]),
            returnValue: _FakeSong_0(
              this,
              Invocation.method(#saveSong, [song]),
            ),
            returnValueForMissingStub: _FakeSong_0(
              this,
              Invocation.method(#saveSong, [song]),
            ),
          )
          as _i2.Song);

  @override
  List<_i2.Song> saveSongs(List<_i2.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#saveSongs, [songs]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  int getSongCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSongCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.Song getSongByPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getSongByPath, [path]),
            returnValue: _FakeSong_0(
              this,
              Invocation.method(#getSongByPath, [path]),
            ),
            returnValueForMissingStub: _FakeSong_0(
              this,
              Invocation.method(#getSongByPath, [path]),
            ),
          )
          as _i2.Song);

  @override
  _i2.Song? getSongByFileHash(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#getSongByFileHash, [fileHash]),
            returnValueForMissingStub: null,
          )
          as _i2.Song?);

  @override
  _i2.Song getSong(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSong, [id]),
            returnValue: _FakeSong_0(this, Invocation.method(#getSong, [id])),
            returnValueForMissingStub: _FakeSong_0(
              this,
              Invocation.method(#getSong, [id]),
            ),
          )
          as _i2.Song);

  @override
  _i2.Song? getSongContaining(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSongContaining, [query]),
            returnValueForMissingStub: null,
          )
          as _i2.Song?);

  @override
  List<_i2.Song> getRecentlyPlayedSongs(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayedSongs, [limit]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getMostPlayedSongs(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getMostPlayedSongs, [limit]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getFavoriteSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteSongs, []),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getSongs(String? query, String? sortField, bool? ascending) =>
      (super.noSuchMethod(
            Invocation.method(#getSongs, [query, sortField, ascending]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getSongsPaged(
    String? query,
    String? sortField,
    bool? ascending,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsPaged, [
              query,
              sortField,
              ascending,
              offset,
              limit,
            ]),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getAllSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSongs, []),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  List<_i2.Song> getUnsyncedSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedSongs, []),
            returnValue: <_i2.Song>[],
            returnValueForMissingStub: <_i2.Song>[],
          )
          as List<_i2.Song>);

  @override
  void deleteSong(_i2.Song? song) => super.noSuchMethod(
    Invocation.method(#deleteSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSong(_i2.Song? song) => super.noSuchMethod(
    Invocation.method(#updateSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSongs(List<_i2.Song>? songs) => super.noSuchMethod(
    Invocation.method(#updateSongs, [songs]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SongRestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRestService extends _i1.Mock implements _i12.SongRestService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set authService(_i3.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i14.NegotiationResponseDto?> negotiateUpload(
    _i15.NegotiationRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#negotiateUpload, [request]),
            returnValue: _i11.Future<_i14.NegotiationResponseDto?>.value(),
            returnValueForMissingStub:
                _i11.Future<_i14.NegotiationResponseDto?>.value(),
          )
          as _i11.Future<_i14.NegotiationResponseDto?>);

  @override
  _i11.Future<bool> uploadChunk({
    required String? fileHash,
    required int? chunkIndex,
    required List<int>? chunkBytes,
    required String? hash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadChunk, [], {
              #fileHash: fileHash,
              #chunkIndex: chunkIndex,
              #chunkBytes: chunkBytes,
              #hash: hash,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i2.Song?> finalizeSong(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeSong, [fileHash]),
            returnValue: _i11.Future<_i2.Song?>.value(),
            returnValueForMissingStub: _i11.Future<_i2.Song?>.value(),
          )
          as _i11.Future<_i2.Song?>);

  @override
  _i11.Future<bool> uploadFullSong({
    required String? audioFilePath,
    required String? name,
    required String? artistName,
    required String? albumName,
    required int? durationInSeconds,
    required int? trackNumber,
    required int? discNumber,
    required int? releaseYear,
    required _i16.Uint8List? coverArtBytes,
    required void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFullSong, [], {
              #audioFilePath: audioFilePath,
              #name: name,
              #artistName: artistName,
              #albumName: albumName,
              #durationInSeconds: durationInSeconds,
              #trackNumber: trackNumber,
              #discNumber: discNumber,
              #releaseYear: releaseYear,
              #coverArtBytes: coverArtBytes,
              #onProgress: onProgress,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i2.Song> getServerSong(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#getServerSong, [fileHash]),
            returnValue: _i11.Future<_i2.Song>.value(
              _FakeSong_0(this, Invocation.method(#getServerSong, [fileHash])),
            ),
            returnValueForMissingStub: _i11.Future<_i2.Song>.value(
              _FakeSong_0(this, Invocation.method(#getServerSong, [fileHash])),
            ),
          )
          as _i11.Future<_i2.Song>);

  @override
  _i11.Future<_i4.SongPageDto> getSongsPage({
    String? query,
    int? page = 0,
    int? size = 50,
    String? sort = 'name,asc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsPage, [], {
              #query: query,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getSongsPage, [], {
                  #query: query,
                  #page: page,
                  #size: size,
                  #sort: sort,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getSongsPage, [], {
                  #query: query,
                  #page: page,
                  #size: size,
                  #sort: sort,
                }),
              ),
            ),
          )
          as _i11.Future<_i4.SongPageDto>);

  @override
  _i11.Future<_i4.SongPageDto> getRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, []),
            returnValue: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getRecommendations, []),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getRecommendations, []),
              ),
            ),
          )
          as _i11.Future<_i4.SongPageDto>);

  @override
  _i11.Future<_i4.SongPageDto> getForgottenFavourites() =>
      (super.noSuchMethod(
            Invocation.method(#getForgottenFavourites, []),
            returnValue: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getForgottenFavourites, []),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(
                this,
                Invocation.method(#getForgottenFavourites, []),
              ),
            ),
          )
          as _i11.Future<_i4.SongPageDto>);

  @override
  _i11.Future<_i4.SongPageDto> getQuickDial() =>
      (super.noSuchMethod(
            Invocation.method(#getQuickDial, []),
            returnValue: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(this, Invocation.method(#getQuickDial, [])),
            ),
            returnValueForMissingStub: _i11.Future<_i4.SongPageDto>.value(
              _FakeSongPageDto_2(this, Invocation.method(#getQuickDial, [])),
            ),
          )
          as _i11.Future<_i4.SongPageDto>);

  @override
  _i11.Future<List<_i2.Song>> getAllSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSongs, []),
            returnValue: _i11.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i11.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i11.Future<List<_i2.Song>>);

  @override
  _i11.Future<_i5.Response> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> put(String? endpoint, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> multipartRequest(
    String? method,
    String? endpoint, {
    Map<String, String>? fields,
    List<_i5.MultipartFile>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [method, endpoint],
              {#fields: fields, #files: files},
            ),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> multipartRequestWithProgress(
    String? method,
    String? endpoint,
    _i17.File? file,
    Map<String, String>? fields,
    void Function(int, int)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#multipartRequestWithProgress, [
              method,
              endpoint,
              file,
              fields,
              onProgress,
            ]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i11.Future<_i5.Response>);
}

/// A class which mocks [ArtistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArtistService extends _i1.Mock implements _i18.ArtistService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Stream<dynamic> watchArtists() =>
      (super.noSuchMethod(
            Invocation.method(#watchArtists, []),
            returnValue: _i11.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i11.Stream<dynamic>.empty(),
          )
          as _i11.Stream<dynamic>);

  @override
  _i6.Artist getArtist(int? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtist, [artistId]),
            returnValue: _FakeArtist_4(
              this,
              Invocation.method(#getArtist, [artistId]),
            ),
            returnValueForMissingStub: _FakeArtist_4(
              this,
              Invocation.method(#getArtist, [artistId]),
            ),
          )
          as _i6.Artist);

  @override
  _i6.Artist? getArtistByServerId(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistByServerId, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i6.Artist?);

  @override
  _i11.Future<_i6.Artist?> fetchAndCacheArtistById(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndCacheArtistById, [serverId]),
            returnValue: _i11.Future<_i6.Artist?>.value(),
            returnValueForMissingStub: _i11.Future<_i6.Artist?>.value(),
          )
          as _i11.Future<_i6.Artist?>);

  @override
  _i6.Artist getOrCreateArtist(String? artistName) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateArtist, [artistName]),
            returnValue: _FakeArtist_4(
              this,
              Invocation.method(#getOrCreateArtist, [artistName]),
            ),
            returnValueForMissingStub: _FakeArtist_4(
              this,
              Invocation.method(#getOrCreateArtist, [artistName]),
            ),
          )
          as _i6.Artist);

  @override
  _i6.Artist getArtistByName(String? artistName) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistByName, [artistName]),
            returnValue: _FakeArtist_4(
              this,
              Invocation.method(#getArtistByName, [artistName]),
            ),
            returnValueForMissingStub: _FakeArtist_4(
              this,
              Invocation.method(#getArtistByName, [artistName]),
            ),
          )
          as _i6.Artist);

  @override
  List<_i6.Artist> getAllArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllArtists, []),
            returnValue: <_i6.Artist>[],
            returnValueForMissingStub: <_i6.Artist>[],
          )
          as List<_i6.Artist>);

  @override
  void updateArtist(_i6.Artist? artist) => super.noSuchMethod(
    Invocation.method(#updateArtist, [artist]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i7.ArtistPageDto> getArtistsPage(
    String? query,
    String? sortField,
    bool? ascending,
    int? page,
    int? size,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistsPage, [
              query,
              sortField,
              ascending,
              page,
              size,
            ]),
            returnValue: _i11.Future<_i7.ArtistPageDto>.value(
              _FakeArtistPageDto_5(
                this,
                Invocation.method(#getArtistsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i7.ArtistPageDto>.value(
              _FakeArtistPageDto_5(
                this,
                Invocation.method(#getArtistsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
          )
          as _i11.Future<_i7.ArtistPageDto>);

  @override
  _i6.Artist cacheServerArtist(_i6.Artist? serverArtist) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerArtist, [serverArtist]),
            returnValue: _FakeArtist_4(
              this,
              Invocation.method(#cacheServerArtist, [serverArtist]),
            ),
            returnValueForMissingStub: _FakeArtist_4(
              this,
              Invocation.method(#cacheServerArtist, [serverArtist]),
            ),
          )
          as _i6.Artist);
}

/// A class which mocks [AlbumService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumService extends _i1.Mock implements _i19.AlbumService {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Stream<dynamic> watchAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbums, []),
            returnValue: _i11.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i11.Stream<dynamic>.empty(),
          )
          as _i11.Stream<dynamic>);

  @override
  _i8.Album getAlbum(int? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [albumId]),
            returnValue: _FakeAlbum_6(
              this,
              Invocation.method(#getAlbum, [albumId]),
            ),
            returnValueForMissingStub: _FakeAlbum_6(
              this,
              Invocation.method(#getAlbum, [albumId]),
            ),
          )
          as _i8.Album);

  @override
  _i8.Album? getAlbumByServerId(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumByServerId, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i8.Album?);

  @override
  _i11.Future<_i8.Album?> fetchAndCacheAlbumById(int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndCacheAlbumById, [serverId]),
            returnValue: _i11.Future<_i8.Album?>.value(),
            returnValueForMissingStub: _i11.Future<_i8.Album?>.value(),
          )
          as _i11.Future<_i8.Album?>);

  @override
  _i8.Album getOrCreateAlbum(
    String? albumName,
    int? artistId, {
    _i16.Uint8List? image,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOrCreateAlbum,
              [albumName, artistId],
              {#image: image},
            ),
            returnValue: _FakeAlbum_6(
              this,
              Invocation.method(
                #getOrCreateAlbum,
                [albumName, artistId],
                {#image: image},
              ),
            ),
            returnValueForMissingStub: _FakeAlbum_6(
              this,
              Invocation.method(
                #getOrCreateAlbum,
                [albumName, artistId],
                {#image: image},
              ),
            ),
          )
          as _i8.Album);

  @override
  List<_i8.Album> getAllAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlbums, []),
            returnValue: <_i8.Album>[],
            returnValueForMissingStub: <_i8.Album>[],
          )
          as List<_i8.Album>);

  @override
  void updateAlbum(_i8.Album? album) => super.noSuchMethod(
    Invocation.method(#updateAlbum, [album]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i9.AlbumPageDto> getAlbumsPage(
    String? query,
    String? sortField,
    bool? ascending,
    int? page,
    int? size,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumsPage, [
              query,
              sortField,
              ascending,
              page,
              size,
            ]),
            returnValue: _i11.Future<_i9.AlbumPageDto>.value(
              _FakeAlbumPageDto_7(
                this,
                Invocation.method(#getAlbumsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i9.AlbumPageDto>.value(
              _FakeAlbumPageDto_7(
                this,
                Invocation.method(#getAlbumsPage, [
                  query,
                  sortField,
                  ascending,
                  page,
                  size,
                ]),
              ),
            ),
          )
          as _i11.Future<_i9.AlbumPageDto>);

  @override
  _i8.Album cacheServerAlbum(_i8.Album? serverAlbum) =>
      (super.noSuchMethod(
            Invocation.method(#cacheServerAlbum, [serverAlbum]),
            returnValue: _FakeAlbum_6(
              this,
              Invocation.method(#cacheServerAlbum, [serverAlbum]),
            ),
            returnValueForMissingStub: _FakeAlbum_6(
              this,
              Invocation.method(#cacheServerAlbum, [serverAlbum]),
            ),
          )
          as _i8.Album);
}

/// A class which mocks [DataSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSyncService extends _i1.Mock implements _i20.DataSyncService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set authService(_i3.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i21.SyncResponseDto?> syncUserLibrary({
    required DateTime? lastSyncTime,
    required List<_i22.SongSyncDto>? localChanges,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserLibrary, [], {
              #lastSyncTime: lastSyncTime,
              #localChanges: localChanges,
            }),
            returnValue: _i11.Future<_i21.SyncResponseDto?>.value(),
            returnValueForMissingStub:
                _i11.Future<_i21.SyncResponseDto?>.value(),
          )
          as _i11.Future<_i21.SyncResponseDto?>);

  @override
  _i11.Future<_i5.Response> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#post, [endpoint, body])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#get, [endpoint])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> put(String? endpoint, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#put, [endpoint, body])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(this, Invocation.method(#delete, [endpoint])),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> multipartRequest(
    String? method,
    String? endpoint, {
    Map<String, String>? fields,
    List<_i5.MultipartFile>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [method, endpoint],
              {#fields: fields, #files: files},
            ),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #multipartRequest,
                  [method, endpoint],
                  {#fields: fields, #files: files},
                ),
              ),
            ),
          )
          as _i11.Future<_i5.Response>);

  @override
  _i11.Future<_i5.Response> multipartRequestWithProgress(
    String? method,
    String? endpoint,
    _i17.File? file,
    Map<String, String>? fields,
    void Function(int, int)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#multipartRequestWithProgress, [
              method,
              endpoint,
              file,
              fields,
              onProgress,
            ]),
            returnValue: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#multipartRequestWithProgress, [
                  method,
                  endpoint,
                  file,
                  fields,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i11.Future<_i5.Response>);
}
