// Mocks generated by Mockito 5.4.6 from annotations
// in music_player_frontend/test/core/ui/widgets/player_controls_queue_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:typed_data' as _i16;
import 'dart:ui' as _i17;

import 'package:audio_service/audio_service.dart' as _i14;
import 'package:flutter/cupertino.dart' as _i2;
import 'package:flutter/material.dart' as _i21;
import 'package:just_audio/just_audio.dart' as _i13;
import 'package:mesh_gradient/mesh_gradient.dart' as _i10;
import 'package:miniplayer/miniplayer.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:music_player_frontend/core/entities/abstract/base_entity.dart'
    as _i5;
import 'package:music_player_frontend/core/entities/app_settings.dart' as _i12;
import 'package:music_player_frontend/core/entities/song.dart' as _i4;
import 'package:music_player_frontend/core/providers/abstract/abstract_app_state_provider.dart'
    as _i20;
import 'package:music_player_frontend/core/providers/abstract/queryable_provider.dart'
    as _i6;
import 'package:music_player_frontend/core/providers/audio_provider.dart'
    as _i7;
import 'package:music_player_frontend/core/providers/song_provider.dart'
    as _i18;
import 'package:music_player_frontend/core/services/health_service.dart' as _i8;
import 'package:music_player_frontend/core/services/settings_service.dart'
    as _i9;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_1<T> extends _i1.SmartFake
    implements _i3.BehaviorSubject<T> {
  _FakeBehaviorSubject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublishSubject_2<T> extends _i1.SmartFake
    implements _i3.PublishSubject<T> {
  _FakePublishSubject_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_4<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSong_5 extends _i1.SmartFake implements _i4.Song {
  _FakeSong_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResult_6<T extends _i5.BaseEntity> extends _i1.SmartFake
    implements _i6.PageResult<T> {
  _FakePageResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioProvider_7 extends _i1.SmartFake implements _i7.AudioProvider {
  _FakeAudioProvider_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthService_8 extends _i1.SmartFake implements _i8.HealthService {
  _FakeHealthService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_9 extends _i1.SmartFake
    implements _i9.SettingsService {
  _FakeSettingsService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_10<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake
    implements _i2.GlobalKey<T> {
  _FakeGlobalKey_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnimatedMeshGradientController_11 extends _i1.SmartFake
    implements _i10.AnimatedMeshGradientController {
  _FakeAnimatedMeshGradientController_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeMiniPlayerController_12 extends _i1.SmartFake
    implements _i11.MiniPlayerController {
  _FakeMiniPlayerController_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_13 extends _i1.SmartFake implements _i12.AppSettings {
  _FakeAppSettings_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProvider extends _i1.Mock implements _i7.AudioProvider {
  @override
  _i2.ValueNotifier<_i13.ProcessingState> get processingState =>
      (super.noSuchMethod(
            Invocation.getter(#processingState),
            returnValue: _FakeValueNotifier_0<_i13.ProcessingState>(
              this,
              Invocation.getter(#processingState),
            ),
            returnValueForMissingStub:
                _FakeValueNotifier_0<_i13.ProcessingState>(
                  this,
                  Invocation.getter(#processingState),
                ),
          )
          as _i2.ValueNotifier<_i13.ProcessingState>);

  @override
  _i2.ValueNotifier<bool> get playingNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#playingNotifier),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#playingNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#playingNotifier),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<bool> get repeatNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#repeatNotifier),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#repeatNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#repeatNotifier),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<bool> get shuffleNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#shuffleNotifier),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#shuffleNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#shuffleNotifier),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<bool> get autoPlayNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#autoPlayNotifier),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#autoPlayNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#autoPlayNotifier),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<int> get sliderNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#sliderNotifier),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#sliderNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#sliderNotifier),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<int> get bufferedPositionNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionNotifier),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#bufferedPositionNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#bufferedPositionNotifier),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<double> get volumeNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#volumeNotifier),
            returnValue: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#volumeNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#volumeNotifier),
            ),
          )
          as _i2.ValueNotifier<double>);

  @override
  _i2.ValueNotifier<double> get playbackSpeedNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#playbackSpeedNotifier),
            returnValue: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#playbackSpeedNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#playbackSpeedNotifier),
            ),
          )
          as _i2.ValueNotifier<double>);

  @override
  _i2.ValueNotifier<Duration> get totalDurationNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#totalDurationNotifier),
            returnValue: _FakeValueNotifier_0<Duration>(
              this,
              Invocation.getter(#totalDurationNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<Duration>(
              this,
              Invocation.getter(#totalDurationNotifier),
            ),
          )
          as _i2.ValueNotifier<Duration>);

  @override
  _i2.ValueNotifier<_i4.Song?> get currentSongNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#currentSongNotifier),
            returnValue: _FakeValueNotifier_0<_i4.Song?>(
              this,
              Invocation.getter(#currentSongNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<_i4.Song?>(
              this,
              Invocation.getter(#currentSongNotifier),
            ),
          )
          as _i2.ValueNotifier<_i4.Song?>);

  @override
  _i2.ValueNotifier<bool> get likedNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#likedNotifier),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#likedNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#likedNotifier),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<int> get songPeerCountNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#songPeerCountNotifier),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#songPeerCountNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#songPeerCountNotifier),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  int get currentIndexInNonShuffled =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexInNonShuffled),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get currentIndexInPlaybackQueue =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexInPlaybackQueue),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i4.Song> get playbackQueue =>
      (super.noSuchMethod(
            Invocation.getter(#playbackQueue),
            returnValue: <_i4.Song>[],
            returnValueForMissingStub: <_i4.Song>[],
          )
          as List<_i4.Song>);

  @override
  List<_i4.Song> get normalQueue =>
      (super.noSuchMethod(
            Invocation.getter(#normalQueue),
            returnValue: <_i4.Song>[],
            returnValueForMissingStub: <_i4.Song>[],
          )
          as List<_i4.Song>);

  @override
  set processingState(_i2.ValueNotifier<_i13.ProcessingState>? value) =>
      super.noSuchMethod(
        Invocation.setter(#processingState, value),
        returnValueForMissingStub: null,
      );

  @override
  set playingNotifier(_i2.ValueNotifier<bool>? value) => super.noSuchMethod(
    Invocation.setter(#playingNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set repeatNotifier(_i2.ValueNotifier<bool>? value) => super.noSuchMethod(
    Invocation.setter(#repeatNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set shuffleNotifier(_i2.ValueNotifier<bool>? value) => super.noSuchMethod(
    Invocation.setter(#shuffleNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoPlayNotifier(_i2.ValueNotifier<bool>? value) => super.noSuchMethod(
    Invocation.setter(#autoPlayNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set sliderNotifier(_i2.ValueNotifier<int>? value) => super.noSuchMethod(
    Invocation.setter(#sliderNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set bufferedPositionNotifier(_i2.ValueNotifier<int>? value) =>
      super.noSuchMethod(
        Invocation.setter(#bufferedPositionNotifier, value),
        returnValueForMissingStub: null,
      );

  @override
  set volumeNotifier(_i2.ValueNotifier<double>? value) => super.noSuchMethod(
    Invocation.setter(#volumeNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set playbackSpeedNotifier(_i2.ValueNotifier<double>? value) =>
      super.noSuchMethod(
        Invocation.setter(#playbackSpeedNotifier, value),
        returnValueForMissingStub: null,
      );

  @override
  set totalDurationNotifier(_i2.ValueNotifier<Duration>? value) =>
      super.noSuchMethod(
        Invocation.setter(#totalDurationNotifier, value),
        returnValueForMissingStub: null,
      );

  @override
  _i3.BehaviorSubject<_i14.PlaybackState> get playbackState =>
      (super.noSuchMethod(
            Invocation.getter(#playbackState),
            returnValue: _FakeBehaviorSubject_1<_i14.PlaybackState>(
              this,
              Invocation.getter(#playbackState),
            ),
            returnValueForMissingStub:
                _FakeBehaviorSubject_1<_i14.PlaybackState>(
                  this,
                  Invocation.getter(#playbackState),
                ),
          )
          as _i3.BehaviorSubject<_i14.PlaybackState>);

  @override
  _i3.BehaviorSubject<List<_i14.MediaItem>> get queue =>
      (super.noSuchMethod(
            Invocation.getter(#queue),
            returnValue: _FakeBehaviorSubject_1<List<_i14.MediaItem>>(
              this,
              Invocation.getter(#queue),
            ),
            returnValueForMissingStub:
                _FakeBehaviorSubject_1<List<_i14.MediaItem>>(
                  this,
                  Invocation.getter(#queue),
                ),
          )
          as _i3.BehaviorSubject<List<_i14.MediaItem>>);

  @override
  _i3.BehaviorSubject<String> get queueTitle =>
      (super.noSuchMethod(
            Invocation.getter(#queueTitle),
            returnValue: _FakeBehaviorSubject_1<String>(
              this,
              Invocation.getter(#queueTitle),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_1<String>(
              this,
              Invocation.getter(#queueTitle),
            ),
          )
          as _i3.BehaviorSubject<String>);

  @override
  _i3.BehaviorSubject<_i14.MediaItem?> get mediaItem =>
      (super.noSuchMethod(
            Invocation.getter(#mediaItem),
            returnValue: _FakeBehaviorSubject_1<_i14.MediaItem?>(
              this,
              Invocation.getter(#mediaItem),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_1<_i14.MediaItem?>(
              this,
              Invocation.getter(#mediaItem),
            ),
          )
          as _i3.BehaviorSubject<_i14.MediaItem?>);

  @override
  _i3.BehaviorSubject<_i14.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
            Invocation.getter(#androidPlaybackInfo),
            returnValue: _FakeBehaviorSubject_1<_i14.AndroidPlaybackInfo>(
              this,
              Invocation.getter(#androidPlaybackInfo),
            ),
            returnValueForMissingStub:
                _FakeBehaviorSubject_1<_i14.AndroidPlaybackInfo>(
                  this,
                  Invocation.getter(#androidPlaybackInfo),
                ),
          )
          as _i3.BehaviorSubject<_i14.AndroidPlaybackInfo>);

  @override
  _i3.BehaviorSubject<_i14.RatingStyle> get ratingStyle =>
      (super.noSuchMethod(
            Invocation.getter(#ratingStyle),
            returnValue: _FakeBehaviorSubject_1<_i14.RatingStyle>(
              this,
              Invocation.getter(#ratingStyle),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_1<_i14.RatingStyle>(
              this,
              Invocation.getter(#ratingStyle),
            ),
          )
          as _i3.BehaviorSubject<_i14.RatingStyle>);

  @override
  _i3.PublishSubject<dynamic> get customEvent =>
      (super.noSuchMethod(
            Invocation.getter(#customEvent),
            returnValue: _FakePublishSubject_2<dynamic>(
              this,
              Invocation.getter(#customEvent),
            ),
            returnValueForMissingStub: _FakePublishSubject_2<dynamic>(
              this,
              Invocation.getter(#customEvent),
            ),
          )
          as _i3.PublishSubject<dynamic>);

  @override
  _i3.BehaviorSubject<dynamic> get customState =>
      (super.noSuchMethod(
            Invocation.getter(#customState),
            returnValue: _FakeBehaviorSubject_1<dynamic>(
              this,
              Invocation.getter(#customState),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_1<dynamic>(
              this,
              Invocation.getter(#customState),
            ),
          )
          as _i3.BehaviorSubject<dynamic>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> skipToNext() =>
      (super.noSuchMethod(
            Invocation.method(#skipToNext, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> skipToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#skipToPrevious, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> downloadSong(_i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#downloadSong, [song]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void setPlaybackSpeed(double? speed) => super.noSuchMethod(
    Invocation.method(#setPlaybackSpeed, [speed]),
    returnValueForMissingStub: null,
  );

  @override
  void setVolume(double? volume) => super.noSuchMethod(
    Invocation.method(#setVolume, [volume]),
    returnValueForMissingStub: null,
  );

  @override
  void setRepeat(bool? repeat) => super.noSuchMethod(
    Invocation.method(#setRepeat, [repeat]),
    returnValueForMissingStub: null,
  );

  @override
  void setShuffle(bool? shuffle) => super.noSuchMethod(
    Invocation.method(#setShuffle, [shuffle]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> setShuffleAndWait(bool? shuffle) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleAndWait, [shuffle]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void setAutoPlay(bool? autoPlay) => super.noSuchMethod(
    Invocation.method(#setAutoPlay, [autoPlay]),
    returnValueForMissingStub: null,
  );

  @override
  int getCurrentSongPeerCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSongPeerCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i15.Future<void> setQueueAndPlay(List<_i4.Song>? songs, _i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#setQueueAndPlay, [songs, song]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<Duration> getDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, []),
            returnValue: _i15.Future<Duration>.value(
              _FakeDuration_3(this, Invocation.method(#getDuration, [])),
            ),
            returnValueForMissingStub: _i15.Future<Duration>.value(
              _FakeDuration_3(this, Invocation.method(#getDuration, [])),
            ),
          )
          as _i15.Future<Duration>);

  @override
  _i15.Future<void> addLastToQueue(List<_i4.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#addLastToQueue, [songs]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> addNextToQueue(List<_i4.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#addNextToQueue, [songs]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> removeFromQueue(_i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [song]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setCurrentSongAndPlay(_i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentSongAndPlay, [song]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> likeCurrentSong() =>
      (super.noSuchMethod(
            Invocation.method(#likeCurrentSong, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> updateColorsFromCover(
    _i5.BaseEntity? entity,
    _i16.Uint8List? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateColorsFromCover, [entity, bytes]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void disposeListeners() => super.noSuchMethod(
    Invocation.method(#disposeListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> prepare() =>
      (super.noSuchMethod(
            Invocation.method(#prepare, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromMediaId, [mediaId, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromSearch, [query, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> prepareFromUri(Uri? uri, [Map<String, dynamic>? extras]) =>
      (super.noSuchMethod(
            Invocation.method(#prepareFromUri, [uri, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromMediaId, [mediaId, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromSearch, [query, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> playFromUri(Uri? uri, [Map<String, dynamic>? extras]) =>
      (super.noSuchMethod(
            Invocation.method(#playFromUri, [uri, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> playMediaItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#playMediaItem, [mediaItem]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> click([
    _i14.MediaButton? button = _i14.MediaButton.media,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#click, [button]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> addQueueItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#addQueueItem, [mediaItem]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> addQueueItems(List<_i14.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
            Invocation.method(#addQueueItems, [mediaItems]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> insertQueueItem(int? index, _i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#insertQueueItem, [index, mediaItem]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> updateQueue(List<_i14.MediaItem>? queue) =>
      (super.noSuchMethod(
            Invocation.method(#updateQueue, [queue]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> updateMediaItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateMediaItem, [mediaItem]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> removeQueueItem(_i14.MediaItem? mediaItem) =>
      (super.noSuchMethod(
            Invocation.method(#removeQueueItem, [mediaItem]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> removeQueueItemAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeQueueItemAt, [index]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> fastForward() =>
      (super.noSuchMethod(
            Invocation.method(#fastForward, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> rewind() =>
      (super.noSuchMethod(
            Invocation.method(#rewind, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> skipToQueueItem(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#skipToQueueItem, [index]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setRating(
    _i14.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#setRating, [rating, extras]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setCaptioningEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setCaptioningEnabled, [enabled]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setRepeatMode(_i14.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
            Invocation.method(#setRepeatMode, [repeatMode]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setShuffleMode(_i14.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleMode, [shuffleMode]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> seekBackward(bool? begin) =>
      (super.noSuchMethod(
            Invocation.method(#seekBackward, [begin]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> seekForward(bool? begin) =>
      (super.noSuchMethod(
            Invocation.method(#seekForward, [begin]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#customAction, [name, extras]),
            returnValue: _i15.Future<dynamic>.value(),
            returnValueForMissingStub: _i15.Future<dynamic>.value(),
          )
          as _i15.Future<dynamic>);

  @override
  _i15.Future<void> onTaskRemoved() =>
      (super.noSuchMethod(
            Invocation.method(#onTaskRemoved, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> onNotificationDeleted() =>
      (super.noSuchMethod(
            Invocation.method(#onNotificationDeleted, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<List<_i14.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, [parentMediaId, options]),
            returnValue: _i15.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
            returnValueForMissingStub: _i15.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
          )
          as _i15.Future<List<_i14.MediaItem>>);

  @override
  _i3.ValueStream<Map<String, dynamic>> subscribeToChildren(
    String? parentMediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToChildren, [parentMediaId]),
            returnValue: _FakeValueStream_4<Map<String, dynamic>>(
              this,
              Invocation.method(#subscribeToChildren, [parentMediaId]),
            ),
            returnValueForMissingStub: _FakeValueStream_4<Map<String, dynamic>>(
              this,
              Invocation.method(#subscribeToChildren, [parentMediaId]),
            ),
          )
          as _i3.ValueStream<Map<String, dynamic>>);

  @override
  _i15.Future<_i14.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaItem, [mediaId]),
            returnValue: _i15.Future<_i14.MediaItem?>.value(),
            returnValueForMissingStub: _i15.Future<_i14.MediaItem?>.value(),
          )
          as _i15.Future<_i14.MediaItem?>);

  @override
  _i15.Future<List<_i14.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query, extras]),
            returnValue: _i15.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
            returnValueForMissingStub: _i15.Future<List<_i14.MediaItem>>.value(
              <_i14.MediaItem>[],
            ),
          )
          as _i15.Future<List<_i14.MediaItem>>);

  @override
  _i15.Future<void> androidAdjustRemoteVolume(
    _i14.AndroidVolumeDirection? direction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#androidAdjustRemoteVolume, [direction]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#androidSetRemoteVolume, [volumeIndex]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SongProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongProvider extends _i1.Mock implements _i18.SongProvider {
  @override
  Map<String, dynamic> get sortFields =>
      (super.noSuchMethod(
            Invocation.getter(#sortFields),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get defaultSortField =>
      (super.noSuchMethod(
            Invocation.getter(#defaultSortField),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#defaultSortField),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.getter(#defaultSortField),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> initialize(List<String>? musicDirectories) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [musicDirectories]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void startBackgroundScan() => super.noSuchMethod(
    Invocation.method(#startBackgroundScan, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> cancelBackgroundScan() =>
      (super.noSuchMethod(
            Invocation.method(#cancelBackgroundScan, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i4.Song> enrichSong(_i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#enrichSong, [song]),
            returnValue: _i15.Future<_i4.Song>.value(
              _FakeSong_5(this, Invocation.method(#enrichSong, [song])),
            ),
            returnValueForMissingStub: _i15.Future<_i4.Song>.value(
              _FakeSong_5(this, Invocation.method(#enrichSong, [song])),
            ),
          )
          as _i15.Future<_i4.Song>);

  @override
  _i15.Future<_i4.Song?> fetchEntity(_i5.BaseEntity? song) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEntity, [song]),
            returnValue: _i15.Future<_i4.Song?>.value(),
            returnValueForMissingStub: _i15.Future<_i4.Song?>.value(),
          )
          as _i15.Future<_i4.Song?>);

  @override
  _i15.Future<_i6.PageResult<_i4.Song>> fetchPage(
    String? query,
    String? sortField,
    bool? ascending,
    bool? localOnly,
    int? page,
    int? size, {
    bool? streamOnly = false,
    String? filterAlbumHash,
    String? filterArtistHash,
    int? filterPlaylistId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchPage,
              [query, sortField, ascending, localOnly, page, size],
              {
                #streamOnly: streamOnly,
                #filterAlbumHash: filterAlbumHash,
                #filterArtistHash: filterArtistHash,
                #filterPlaylistId: filterPlaylistId,
              },
            ),
            returnValue: _i15.Future<_i6.PageResult<_i4.Song>>.value(
              _FakePageResult_6<_i4.Song>(
                this,
                Invocation.method(
                  #fetchPage,
                  [query, sortField, ascending, localOnly, page, size],
                  {
                    #streamOnly: streamOnly,
                    #filterAlbumHash: filterAlbumHash,
                    #filterArtistHash: filterArtistHash,
                    #filterPlaylistId: filterPlaylistId,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i6.PageResult<_i4.Song>>.value(
                  _FakePageResult_6<_i4.Song>(
                    this,
                    Invocation.method(
                      #fetchPage,
                      [query, sortField, ascending, localOnly, page, size],
                      {
                        #streamOnly: streamOnly,
                        #filterAlbumHash: filterAlbumHash,
                        #filterArtistHash: filterArtistHash,
                        #filterPlaylistId: filterPlaylistId,
                      },
                    ),
                  ),
                ),
          )
          as _i15.Future<_i6.PageResult<_i4.Song>>);

  @override
  _i15.Future<List<_i4.Song>> fetchRecommendedSongs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecommendedSongs, []),
            returnValue: _i15.Future<List<_i4.Song>>.value(<_i4.Song>[]),
            returnValueForMissingStub: _i15.Future<List<_i4.Song>>.value(
              <_i4.Song>[],
            ),
          )
          as _i15.Future<List<_i4.Song>>);

  @override
  _i15.Future<List<_i4.Song>> fetchRediscoverSongs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRediscoverSongs, []),
            returnValue: _i15.Future<List<_i4.Song>>.value(<_i4.Song>[]),
            returnValueForMissingStub: _i15.Future<List<_i4.Song>>.value(
              <_i4.Song>[],
            ),
          )
          as _i15.Future<List<_i4.Song>>);

  @override
  _i15.Future<List<_i4.Song>> fetchJumpBackSongs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchJumpBackSongs, []),
            returnValue: _i15.Future<List<_i4.Song>>.value(<_i4.Song>[]),
            returnValueForMissingStub: _i15.Future<List<_i4.Song>>.value(
              <_i4.Song>[],
            ),
          )
          as _i15.Future<List<_i4.Song>>);

  @override
  void removeSong(_i4.Song? song) => super.noSuchMethod(
    Invocation.method(#removeSong, [song]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> updateSong(_i4.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#updateSong, [song]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void refreshSongs() => super.noSuchMethod(
    Invocation.method(#refreshSongs, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<_i6.PageResult<_i4.Song>> getSongsPage(
    String? hash, {
    bool? localOnly = false,
    int? page = 0,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSongsPage,
              [hash],
              {#localOnly: localOnly, #page: page, #size: size},
            ),
            returnValue: _i15.Future<_i6.PageResult<_i4.Song>>.value(
              _FakePageResult_6<_i4.Song>(
                this,
                Invocation.method(
                  #getSongsPage,
                  [hash],
                  {#localOnly: localOnly, #page: page, #size: size},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i6.PageResult<_i4.Song>>.value(
                  _FakePageResult_6<_i4.Song>(
                    this,
                    Invocation.method(
                      #getSongsPage,
                      [hash],
                      {#localOnly: localOnly, #page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i15.Future<_i6.PageResult<_i4.Song>>);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AbstractAppStateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractAppStateProvider extends _i1.Mock
    implements _i20.AbstractAppStateProvider {
  @override
  _i7.AudioProvider get audioProvider =>
      (super.noSuchMethod(
            Invocation.getter(#audioProvider),
            returnValue: _FakeAudioProvider_7(
              this,
              Invocation.getter(#audioProvider),
            ),
            returnValueForMissingStub: _FakeAudioProvider_7(
              this,
              Invocation.getter(#audioProvider),
            ),
          )
          as _i7.AudioProvider);

  @override
  _i8.HealthService get healthService =>
      (super.noSuchMethod(
            Invocation.getter(#healthService),
            returnValue: _FakeHealthService_8(
              this,
              Invocation.getter(#healthService),
            ),
            returnValueForMissingStub: _FakeHealthService_8(
              this,
              Invocation.getter(#healthService),
            ),
          )
          as _i8.HealthService);

  @override
  _i9.SettingsService get settingsService =>
      (super.noSuchMethod(
            Invocation.getter(#settingsService),
            returnValue: _FakeSettingsService_9(
              this,
              Invocation.getter(#settingsService),
            ),
            returnValueForMissingStub: _FakeSettingsService_9(
              this,
              Invocation.getter(#settingsService),
            ),
          )
          as _i9.SettingsService);

  @override
  _i2.GlobalKey<_i2.NavigatorState> get innerNavigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#innerNavigatorKey),
            returnValue: _FakeGlobalKey_10<_i2.NavigatorState>(
              this,
              Invocation.getter(#innerNavigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_10<_i2.NavigatorState>(
              this,
              Invocation.getter(#innerNavigatorKey),
            ),
          )
          as _i2.GlobalKey<_i2.NavigatorState>);

  @override
  _i2.GlobalKey<_i2.NavigatorState> get outerNavigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#outerNavigatorKey),
            returnValue: _FakeGlobalKey_10<_i2.NavigatorState>(
              this,
              Invocation.getter(#outerNavigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_10<_i2.NavigatorState>(
              this,
              Invocation.getter(#outerNavigatorKey),
            ),
          )
          as _i2.GlobalKey<_i2.NavigatorState>);

  @override
  _i2.GlobalKey<_i21.ScaffoldState> get scaffoldKey =>
      (super.noSuchMethod(
            Invocation.getter(#scaffoldKey),
            returnValue: _FakeGlobalKey_10<_i21.ScaffoldState>(
              this,
              Invocation.getter(#scaffoldKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_10<_i21.ScaffoldState>(
              this,
              Invocation.getter(#scaffoldKey),
            ),
          )
          as _i2.GlobalKey<_i21.ScaffoldState>);

  @override
  _i10.AnimatedMeshGradientController get gradientController =>
      (super.noSuchMethod(
            Invocation.getter(#gradientController),
            returnValue: _FakeAnimatedMeshGradientController_11(
              this,
              Invocation.getter(#gradientController),
            ),
            returnValueForMissingStub: _FakeAnimatedMeshGradientController_11(
              this,
              Invocation.getter(#gradientController),
            ),
          )
          as _i10.AnimatedMeshGradientController);

  @override
  _i11.MiniPlayerController get miniPlayerController =>
      (super.noSuchMethod(
            Invocation.getter(#miniPlayerController),
            returnValue: _FakeMiniPlayerController_12(
              this,
              Invocation.getter(#miniPlayerController),
            ),
            returnValueForMissingStub: _FakeMiniPlayerController_12(
              this,
              Invocation.getter(#miniPlayerController),
            ),
          )
          as _i11.MiniPlayerController);

  @override
  _i12.AppSettings get appSettings =>
      (super.noSuchMethod(
            Invocation.getter(#appSettings),
            returnValue: _FakeAppSettings_13(
              this,
              Invocation.getter(#appSettings),
            ),
            returnValueForMissingStub: _FakeAppSettings_13(
              this,
              Invocation.getter(#appSettings),
            ),
          )
          as _i12.AppSettings);

  @override
  List<String> get appActions =>
      (super.noSuchMethod(
            Invocation.getter(#appActions),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get isFullScreen =>
      (super.noSuchMethod(
            Invocation.getter(#isFullScreen),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get currentDrawerIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentDrawerIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.ValueNotifier<bool> get isPanelOpen =>
      (super.noSuchMethod(
            Invocation.getter(#isPanelOpen),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isPanelOpen),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isPanelOpen),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<double> get opacityNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#opacityNotifier),
            returnValue: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#opacityNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<double>(
              this,
              Invocation.getter(#opacityNotifier),
            ),
          )
          as _i2.ValueNotifier<double>);

  @override
  _i2.ValueNotifier<int> get refreshRequestNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#refreshRequestNotifier),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#refreshRequestNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#refreshRequestNotifier),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<bool> get shouldDisplayLocalOnly =>
      (super.noSuchMethod(
            Invocation.getter(#shouldDisplayLocalOnly),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#shouldDisplayLocalOnly),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#shouldDisplayLocalOnly),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<_i2.Widget> get connectivityStatusNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStatusNotifier),
            returnValue: _FakeValueNotifier_0<_i2.Widget>(
              this,
              Invocation.getter(#connectivityStatusNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<_i2.Widget>(
              this,
              Invocation.getter(#connectivityStatusNotifier),
            ),
          )
          as _i2.ValueNotifier<_i2.Widget>);

  @override
  List<_i17.Color> get colors =>
      (super.noSuchMethod(
            Invocation.getter(#colors),
            returnValue: <_i17.Color>[],
            returnValueForMissingStub: <_i17.Color>[],
          )
          as List<_i17.Color>);

  @override
  set appSettings(_i12.AppSettings? value) => super.noSuchMethod(
    Invocation.setter(#appSettings, value),
    returnValueForMissingStub: null,
  );

  @override
  set appActions(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#appActions, value),
    returnValueForMissingStub: null,
  );

  @override
  set isFullScreen(bool? value) => super.noSuchMethod(
    Invocation.setter(#isFullScreen, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentDrawerIndex(int? value) => super.noSuchMethod(
    Invocation.setter(#currentDrawerIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  set isPanelOpen(_i2.ValueNotifier<bool>? value) => super.noSuchMethod(
    Invocation.setter(#isPanelOpen, value),
    returnValueForMissingStub: null,
  );

  @override
  set opacityNotifier(_i2.ValueNotifier<double>? value) => super.noSuchMethod(
    Invocation.setter(#opacityNotifier, value),
    returnValueForMissingStub: null,
  );

  @override
  set refreshRequestNotifier(_i2.ValueNotifier<int>? value) =>
      super.noSuchMethod(
        Invocation.setter(#refreshRequestNotifier, value),
        returnValueForMissingStub: null,
      );

  @override
  set shouldDisplayLocalOnly(_i2.ValueNotifier<bool>? value) =>
      super.noSuchMethod(
        Invocation.setter(#shouldDisplayLocalOnly, value),
        returnValueForMissingStub: null,
      );

  @override
  set connectivityStatusNotifier(_i2.ValueNotifier<_i2.Widget>? value) =>
      super.noSuchMethod(
        Invocation.setter(#connectivityStatusNotifier, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void requestRefresh() => super.noSuchMethod(
    Invocation.method(#requestRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateAppSettings() => super.noSuchMethod(
    Invocation.method(#updateAppSettings, []),
    returnValueForMissingStub: null,
  );

  @override
  void setDrawerOpen(bool? isOpen) => super.noSuchMethod(
    Invocation.method(#setDrawerOpen, [isOpen]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Widget? getEndDrawer(_i2.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getEndDrawer, [context]),
            returnValueForMissingStub: null,
          )
          as _i2.Widget?);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
