sonar.sources=lib
sonar.tests=test,integration_test
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/main*.dart,lib/**/objectbox.g.dart
sonar.exclusions=lib/**/objectbox.g.dart,lib/core/database/objectbox-model.json
sonar.cpd.exclusions=lib/**/objectbox.g.dart
sonar.sourceEncoding=UTF-8
