// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../core/entities/album.dart';
import '../../core/entities/app_settings.dart';
import '../../core/entities/artist.dart';
import '../../core/entities/audio_settings.dart';
import '../../core/entities/playlist.dart';
import '../../core/entities/song.dart';
import '../../core/entities/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5434110965985548662),
    name: 'Album',
    lastPropertyId: const obx_int.IdUid(3, 407877923627896617),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7032580492777901318),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5544579394423112026),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 407877923627896617),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7460723377333623315),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5636332516459031152),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(3, 7650922049008629566),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8182695408861448713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4814418086711149227),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3299821873480654513),
        relationTarget: 'User',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7650922049008629566),
        name: 'missingSongs',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 286855446892723846),
    name: 'Artist',
    lastPropertyId: const obx_int.IdUid(3, 5416451551965956234),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4328875806142310070),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5323548150098807575),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5416451551965956234),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 1922746581072921885),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 125102733176896809),
    name: 'AudioSettings',
    lastPropertyId: const obx_int.IdUid(11, 8760273509754657128),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5477265908356053087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8600891691394737110),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5495534843995516530),
        relationTarget: 'User',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1712099644485876943),
        name: 'index',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4469033242742600143),
        name: 'slider',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8073265993596439316),
        name: 'repeat',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1400504775426850532),
        name: 'shuffle',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2306020798377727376),
        name: 'balance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 544190301642256248),
        name: 'speed',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5535822755287570937),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4849993503317089340),
        name: 'queue',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8760273509754657128),
        name: 'shuffledQueue',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8253375800311252238),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(9, 1802919749950013416),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8434415855449134709),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3455489451381713443),
        name: 'indestructible',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2943805729086177467),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2645844746166457040),
        name: 'nextAdded',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4543366596315292496),
        name: 'pathsInOrder',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5782041773266088141),
        name: 'artistCount',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3786128439205850546),
        name: 'coverArt',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2530901746877373657),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1802919749950013416),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 1387782578054686999),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5328859898643810358),
    name: 'Song',
    lastPropertyId: const obx_int.IdUid(16, 4145861533755825969),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8349890911918800237),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5064592112988109331),
        name: 'path',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 5875477887538721059),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 398563368122461455),
        name: 'lyricsPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1158660851052252113),
        name: 'genre',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7149598354745784686),
        name: 'trackArtist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1569902295142124546),
        name: 'album',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1008458843636792636),
        name: 'albumArtist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2092422769119360865),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4990231509912090547),
        name: 'trackNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1705812540767964011),
        name: 'discNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4172274590478861863),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8421888090370908218),
        name: 'lastPlayed',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9200305186945584370),
        name: 'playCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1951961947720040855),
        name: 'liked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5072589520708592835),
        name: 'fullyLoaded',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4145861533755825969),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5686730227622637123),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(6, 4547713415112261797),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4168045132000032814),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4471228529824775381),
        name: 'mongoID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3735463316115781249),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1890088438278972916),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7438866839967098830),
        name: 'deviceList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4547713415112261797),
        name: 'primaryDevice',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 5686730227622637123),
    lastIndexId: const obx_int.IdUid(3, 5875477887538721059),
    lastRelationId: const obx_int.IdUid(3, 1387782578054686999),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Album: obx_int.EntityDefinition<Album>(
      model: _entities[0],
      toOneRelations: (Album object) => [],
      toManyRelations: (Album object) => {
        obx_int.RelInfo<Album>.toMany(1, object.id): object.songs,
      },
      getId: (Album object) => object.id,
      setId: (Album object, int id) {
        object.id = id;
      },
      objectToFB: (Album object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.duration);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Album()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '');
        obx_int.InternalToManyAccess.setRelInfo<Album>(
          object.songs,
          store,
          obx_int.RelInfo<Album>.toMany(1, object.id),
        );
        return object;
      },
    ),
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[1],
      toOneRelations: (AppSettings object) => [object.user],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        final missingSongsOffset = fbb.writeList(
          object.missingSongs.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.user.targetId);
        fbb.addOffset(2, missingSongsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..missingSongs = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 8, []);
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
    Artist: obx_int.EntityDefinition<Artist>(
      model: _entities[2],
      toOneRelations: (Artist object) => [],
      toManyRelations: (Artist object) => {
        obx_int.RelInfo<Artist>.toMany(2, object.id): object.songs,
      },
      getId: (Artist object) => object.id,
      setId: (Artist object, int id) {
        object.id = id;
      },
      objectToFB: (Artist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.duration);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Artist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '');
        obx_int.InternalToManyAccess.setRelInfo<Artist>(
          object.songs,
          store,
          obx_int.RelInfo<Artist>.toMany(2, object.id),
        );
        return object;
      },
    ),
    AudioSettings: obx_int.EntityDefinition<AudioSettings>(
      model: _entities[3],
      toOneRelations: (AudioSettings object) => [object.user],
      toManyRelations: (AudioSettings object) => {},
      getId: (AudioSettings object) => object.id,
      setId: (AudioSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AudioSettings object, fb.Builder fbb) {
        final queueOffset = fbb.writeList(
          object.queue.map(fbb.writeString).toList(growable: false),
        );
        final shuffledQueueOffset = fbb.writeList(
          object.shuffledQueue.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.user.targetId);
        fbb.addInt64(2, object.index);
        fbb.addInt64(3, object.slider);
        fbb.addBool(4, object.repeat);
        fbb.addBool(5, object.shuffle);
        fbb.addFloat64(6, object.balance);
        fbb.addFloat64(7, object.speed);
        fbb.addFloat64(8, object.volume);
        fbb.addOffset(9, queueOffset);
        fbb.addOffset(10, shuffledQueueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AudioSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..index = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..slider = const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
          ..repeat = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..shuffle = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..balance = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..speed = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..volume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..queue = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 22, [])
          ..shuffledQueue = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 24, []);
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[4],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {
        obx_int.RelInfo<Playlist>.toMany(3, object.id): object.songs,
      },
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final nextAddedOffset = fbb.writeString(object.nextAdded);
        final pathsInOrderOffset = fbb.writeList(
          object.pathsInOrder.map(fbb.writeString).toList(growable: false),
        );
        final artistCountOffset = fbb.writeList(
          object.artistCount.map(fbb.writeString).toList(growable: false),
        );
        final coverArtOffset = object.coverArt == null
            ? null
            : fbb.writeListInt8(object.coverArt!);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.indestructible);
        fbb.addInt64(2, object.duration);
        fbb.addOffset(3, nextAddedOffset);
        fbb.addOffset(4, pathsInOrderOffset);
        fbb.addOffset(5, artistCountOffset);
        fbb.addOffset(6, coverArtOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(8, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Playlist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..indestructible = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          )
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..nextAdded = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..pathsInOrder = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 12, [])
          ..artistCount = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 14, [])
          ..coverArt =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 16)
                  as Uint8List?
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '');
        obx_int.InternalToManyAccess.setRelInfo<Playlist>(
          object.songs,
          store,
          obx_int.RelInfo<Playlist>.toMany(3, object.id),
        );
        return object;
      },
    ),
    Song: obx_int.EntityDefinition<Song>(
      model: _entities[5],
      toOneRelations: (Song object) => [],
      toManyRelations: (Song object) => {},
      getId: (Song object) => object.id,
      setId: (Song object, int id) {
        object.id = id;
      },
      objectToFB: (Song object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final lyricsPathOffset = fbb.writeString(object.lyricsPath);
        final genreOffset = fbb.writeString(object.genre);
        final trackArtistOffset = fbb.writeString(object.trackArtist);
        final albumOffset = fbb.writeString(object.album);
        final albumArtistOffset = fbb.writeString(object.albumArtist);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addOffset(2, lyricsPathOffset);
        fbb.addOffset(3, genreOffset);
        fbb.addOffset(4, trackArtistOffset);
        fbb.addOffset(5, albumOffset);
        fbb.addOffset(6, albumArtistOffset);
        fbb.addInt64(7, object.duration);
        fbb.addInt64(8, object.trackNumber);
        fbb.addInt64(9, object.discNumber);
        fbb.addInt64(10, object.year);
        fbb.addInt64(11, object.lastPlayed?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.playCount);
        fbb.addBool(13, object.liked);
        fbb.addBool(14, object.fullyLoaded);
        fbb.addOffset(15, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastPlayedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = Song()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..path = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..lyricsPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..genre = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..trackArtist = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..album = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..albumArtist = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..trackNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..discNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..year = const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
          ..lastPlayed = lastPlayedValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastPlayedValue)
          ..playCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          )
          ..liked = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            30,
            false,
          )
          ..fullyLoaded = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            32,
            false,
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '');

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[6],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final mongoIDOffset = fbb.writeString(object.mongoID);
        final emailOffset = fbb.writeString(object.email);
        final passwordOffset = fbb.writeString(object.password);
        final deviceListOffset = fbb.writeList(
          object.deviceList.map(fbb.writeString).toList(growable: false),
        );
        final primaryDeviceOffset = fbb.writeString(object.primaryDevice);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, mongoIDOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, passwordOffset);
        fbb.addOffset(4, deviceListOffset);
        fbb.addOffset(5, primaryDeviceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = User()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..mongoID = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..password = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..deviceList = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 12, [])
          ..primaryDevice = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Album] entity fields to define ObjectBox queries.
class Album_ {
  /// See [Album.id].
  static final id = obx.QueryIntegerProperty<Album>(_entities[0].properties[0]);

  /// See [Album.duration].
  static final duration = obx.QueryIntegerProperty<Album>(
    _entities[0].properties[1],
  );

  /// See [Album.name].
  static final name = obx.QueryStringProperty<Album>(
    _entities[0].properties[2],
  );

  /// see [Album.songs]
  static final songs = obx.QueryRelationToMany<Album, Song>(
    _entities[0].relations[0],
  );
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[0],
  );

  /// See [AppSettings.user].
  static final user = obx.QueryRelationToOne<AppSettings, User>(
    _entities[1].properties[1],
  );

  /// See [AppSettings.missingSongs].
  static final missingSongs = obx.QueryStringVectorProperty<AppSettings>(
    _entities[1].properties[2],
  );
}

/// [Artist] entity fields to define ObjectBox queries.
class Artist_ {
  /// See [Artist.id].
  static final id = obx.QueryIntegerProperty<Artist>(
    _entities[2].properties[0],
  );

  /// See [Artist.duration].
  static final duration = obx.QueryIntegerProperty<Artist>(
    _entities[2].properties[1],
  );

  /// See [Artist.name].
  static final name = obx.QueryStringProperty<Artist>(
    _entities[2].properties[2],
  );

  /// see [Artist.songs]
  static final songs = obx.QueryRelationToMany<Artist, Song>(
    _entities[2].relations[0],
  );
}

/// [AudioSettings] entity fields to define ObjectBox queries.
class AudioSettings_ {
  /// See [AudioSettings.id].
  static final id = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[0],
  );

  /// See [AudioSettings.user].
  static final user = obx.QueryRelationToOne<AudioSettings, User>(
    _entities[3].properties[1],
  );

  /// See [AudioSettings.index].
  static final index = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[2],
  );

  /// See [AudioSettings.slider].
  static final slider = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[3],
  );

  /// See [AudioSettings.repeat].
  static final repeat = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[4],
  );

  /// See [AudioSettings.shuffle].
  static final shuffle = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[5],
  );

  /// See [AudioSettings.balance].
  static final balance = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[6],
  );

  /// See [AudioSettings.speed].
  static final speed = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[7],
  );

  /// See [AudioSettings.volume].
  static final volume = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[8],
  );

  /// See [AudioSettings.queue].
  static final queue = obx.QueryStringVectorProperty<AudioSettings>(
    _entities[3].properties[9],
  );

  /// See [AudioSettings.shuffledQueue].
  static final shuffledQueue = obx.QueryStringVectorProperty<AudioSettings>(
    _entities[3].properties[10],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[4].properties[0],
  );

  /// See [Playlist.indestructible].
  static final indestructible = obx.QueryBooleanProperty<Playlist>(
    _entities[4].properties[1],
  );

  /// See [Playlist.duration].
  static final duration = obx.QueryIntegerProperty<Playlist>(
    _entities[4].properties[2],
  );

  /// See [Playlist.nextAdded].
  static final nextAdded = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[3],
  );

  /// See [Playlist.pathsInOrder].
  static final pathsInOrder = obx.QueryStringVectorProperty<Playlist>(
    _entities[4].properties[4],
  );

  /// See [Playlist.artistCount].
  static final artistCount = obx.QueryStringVectorProperty<Playlist>(
    _entities[4].properties[5],
  );

  /// See [Playlist.coverArt].
  static final coverArt = obx.QueryByteVectorProperty<Playlist>(
    _entities[4].properties[6],
  );

  /// See [Playlist.createdAt].
  static final createdAt = obx.QueryDateProperty<Playlist>(
    _entities[4].properties[7],
  );

  /// See [Playlist.name].
  static final name = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[8],
  );

  /// see [Playlist.songs]
  static final songs = obx.QueryRelationToMany<Playlist, Song>(
    _entities[4].relations[0],
  );
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// See [Song.id].
  static final id = obx.QueryIntegerProperty<Song>(_entities[5].properties[0]);

  /// See [Song.path].
  static final path = obx.QueryStringProperty<Song>(_entities[5].properties[1]);

  /// See [Song.lyricsPath].
  static final lyricsPath = obx.QueryStringProperty<Song>(
    _entities[5].properties[2],
  );

  /// See [Song.genre].
  static final genre = obx.QueryStringProperty<Song>(
    _entities[5].properties[3],
  );

  /// See [Song.trackArtist].
  static final trackArtist = obx.QueryStringProperty<Song>(
    _entities[5].properties[4],
  );

  /// See [Song.album].
  static final album = obx.QueryStringProperty<Song>(
    _entities[5].properties[5],
  );

  /// See [Song.albumArtist].
  static final albumArtist = obx.QueryStringProperty<Song>(
    _entities[5].properties[6],
  );

  /// See [Song.duration].
  static final duration = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[7],
  );

  /// See [Song.trackNumber].
  static final trackNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[8],
  );

  /// See [Song.discNumber].
  static final discNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[9],
  );

  /// See [Song.year].
  static final year = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[10],
  );

  /// See [Song.lastPlayed].
  static final lastPlayed = obx.QueryDateProperty<Song>(
    _entities[5].properties[11],
  );

  /// See [Song.playCount].
  static final playCount = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[12],
  );

  /// See [Song.liked].
  static final liked = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[13],
  );

  /// See [Song.fullyLoaded].
  static final fullyLoaded = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[14],
  );

  /// See [Song.name].
  static final name = obx.QueryStringProperty<Song>(
    _entities[5].properties[15],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[6].properties[0]);

  /// See [User.mongoID].
  static final mongoID = obx.QueryStringProperty<User>(
    _entities[6].properties[1],
  );

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[6].properties[2],
  );

  /// See [User.password].
  static final password = obx.QueryStringProperty<User>(
    _entities[6].properties[3],
  );

  /// See [User.deviceList].
  static final deviceList = obx.QueryStringVectorProperty<User>(
    _entities[6].properties[4],
  );

  /// See [User.primaryDevice].
  static final primaryDevice = obx.QueryStringProperty<User>(
    _entities[6].properties[5],
  );
}
