// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../core/entities/album.dart';
import '../../core/entities/app_settings.dart';
import '../../core/entities/artist.dart';
import '../../core/entities/audio_settings.dart';
import '../../core/entities/played_song.dart';
import '../../core/entities/playlist.dart';
import '../../core/entities/playlist_song.dart';
import '../../core/entities/queue_song.dart';
import '../../core/entities/song.dart';
import '../../core/entities/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5434110965985548662),
    name: 'Album',
    lastPropertyId: const obx_int.IdUid(9, 8887715385877929801),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7032580492777901318),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 407877923627896617),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1723867092633600964),
        name: 'artistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 1626958777364333393),
        relationTarget: 'Artist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8887715385877929801),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7460723377333623315),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5636332516459031152),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(10, 5824882614796350963),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8182695408861448713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7350112739434599895),
        name: 'firstTime',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7187739893577837077),
        name: 'systemTray',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8807803993324951881),
        name: 'fullClose',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2971545764559009366),
        name: 'mainSongPlace',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3530066872263334473),
        name: 'songPlaces',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4299180230132809907),
        name: 'songPlaceIncludeSubfolders',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5824882614796350963),
        name: 'drawerOpen',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 286855446892723846),
    name: 'Artist',
    lastPropertyId: const obx_int.IdUid(3, 5416451551965956234),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4328875806142310070),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5416451551965956234),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 1922746581072921885),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'albums',
        srcEntity: 'Album',
        srcField: 'artist',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 125102733176896809),
    name: 'AudioSettings',
    lastPropertyId: const obx_int.IdUid(11, 8760273509754657128),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5477265908356053087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1712099644485876943),
        name: 'index',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8073265993596439316),
        name: 'repeat',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1400504775426850532),
        name: 'shuffle',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2306020798377727376),
        name: 'balance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 544190301642256248),
        name: 'speed',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5535822755287570937),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8253375800311252238),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(11, 966267869899998642),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8434415855449134709),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3455489451381713443),
        name: 'indestructible',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2645844746166457040),
        name: 'nextAdded',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2530901746877373657),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1802919749950013416),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 966267869899998642),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 1676580428239258720),
        name: 'playlistSongs',
        targetId: const obx_int.IdUid(9, 8147548360535687209),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5328859898643810358),
    name: 'Song',
    lastPropertyId: const obx_int.IdUid(18, 7424054812745538720),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8349890911918800237),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5064592112988109331),
        name: 'path',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 5875477887538721059),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 398563368122461455),
        name: 'lyricsPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2092422769119360865),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4990231509912090547),
        name: 'trackNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1705812540767964011),
        name: 'discNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4172274590478861863),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1951961947720040855),
        name: 'liked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5072589520708592835),
        name: 'fullyLoaded',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4145861533755825969),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2204895483700977006),
        name: 'artistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 774830058903062476),
        relationTarget: 'Artist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7424054812745538720),
        name: 'albumId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 6060959533894279167),
        relationTarget: 'Album',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5686730227622637123),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(6, 4547713415112261797),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4168045132000032814),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4471228529824775381),
        name: 'mongoID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3735463316115781249),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1890088438278972916),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7438866839967098830),
        name: 'deviceList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4547713415112261797),
        name: 'primaryDevice',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 4825632188467975262),
    name: 'PlayedSong',
    lastPropertyId: const obx_int.IdUid(4, 8651225088868707378),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2669617878670335734),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7010134823570654351),
        name: 'songId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 7294647678718152494),
        relationTarget: 'Song',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8626844870117654806),
        name: 'playedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8651225088868707378),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8147548360535687209),
    name: 'PlaylistSong',
    lastPropertyId: const obx_int.IdUid(4, 5438557649624740852),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4331356309693753328),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4313796314850674183),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 877664949696669408),
        relationTarget: 'Playlist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2784386784936256907),
        name: 'songId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 8270159122959522767),
        relationTarget: 'Song',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5438557649624740852),
        name: 'order',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 1656493538472770553),
    name: 'QueueSong',
    lastPropertyId: const obx_int.IdUid(3, 1080393989965147079),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7588651334738479868),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3374299748312447501),
        name: 'songId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 8002948864735007026),
        relationTarget: 'Song',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1080393989965147079),
        name: 'position',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 1656493538472770553),
    lastIndexId: const obx_int.IdUid(10, 8002948864735007026),
    lastRelationId: const obx_int.IdUid(5, 1676580428239258720),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [3299821873480654513, 5495534843995516530],
    retiredPropertyUids: const [
      1158660851052252113,
      7149598354745784686,
      1569902295142124546,
      1008458843636792636,
      5544579394423112026,
      5323548150098807575,
      2943805729086177467,
      5782041773266088141,
      1840321970361704243,
      4814418086711149227,
      7650922049008629566,
      8600891691394737110,
      4543366596315292496,
      1533051777349163043,
      8421888090370908218,
      9200305186945584370,
      3462329237618661875,
      3786128439205850546,
      8350880238422885241,
      4724448620056894215,
      4849993503317089340,
      8760273509754657128,
      4469033242742600143,
    ],
    retiredRelationUids: const [1387782578054686999, 4329599273410235920],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Album: obx_int.EntityDefinition<Album>(
      model: _entities[0],
      toOneRelations: (Album object) => [object.artist],
      toManyRelations: (Album object) => {
        obx_int.RelInfo<Album>.toMany(1, object.id): object.songs,
      },
      getId: (Album object) => object.id,
      setId: (Album object, int id) {
        object.id = id;
      },
      objectToFB: (Album object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt8(object.imageBytes!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(7, object.artist.targetId);
        fbb.addOffset(8, imageBytesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Album()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..imageBytes =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 20)
                  as Uint8List?;
        object.artist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.artist.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Album>(
          object.songs,
          store,
          obx_int.RelInfo<Album>.toMany(1, object.id),
        );
        return object;
      },
    ),
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[1],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        final mainSongPlaceOffset = fbb.writeString(object.mainSongPlace);
        final songPlacesOffset = fbb.writeList(
          object.songPlaces.map(fbb.writeString).toList(growable: false),
        );
        final songPlaceIncludeSubfoldersOffset = fbb.writeListInt64(
          object.songPlaceIncludeSubfolders,
        );
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addBool(3, object.firstTime);
        fbb.addBool(4, object.systemTray);
        fbb.addBool(5, object.fullClose);
        fbb.addOffset(6, mainSongPlaceOffset);
        fbb.addOffset(7, songPlacesOffset);
        fbb.addOffset(8, songPlaceIncludeSubfoldersOffset);
        fbb.addBool(9, object.drawerOpen);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..firstTime = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..systemTray = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..fullClose = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..mainSongPlace = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..songPlaces = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 18, [])
          ..songPlaceIncludeSubfolders = const fb.ListReader<int>(
            fb.Int64Reader(),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 20, [])
          ..drawerOpen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          );

        return object;
      },
    ),
    Artist: obx_int.EntityDefinition<Artist>(
      model: _entities[2],
      toOneRelations: (Artist object) => [],
      toManyRelations: (Artist object) => {
        obx_int.RelInfo<Artist>.toMany(2, object.id): object.songs,
        obx_int.RelInfo<Album>.toOneBacklink(
          8,
          object.id,
          (Album srcObject) => srcObject.artist,
        ): object.albums,
      },
      getId: (Artist object) => object.id,
      setId: (Artist object, int id) {
        object.id = id;
      },
      objectToFB: (Artist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Artist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '');
        obx_int.InternalToManyAccess.setRelInfo<Artist>(
          object.songs,
          store,
          obx_int.RelInfo<Artist>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Artist>(
          object.albums,
          store,
          obx_int.RelInfo<Album>.toOneBacklink(
            8,
            object.id,
            (Album srcObject) => srcObject.artist,
          ),
        );
        return object;
      },
    ),
    AudioSettings: obx_int.EntityDefinition<AudioSettings>(
      model: _entities[3],
      toOneRelations: (AudioSettings object) => [],
      toManyRelations: (AudioSettings object) => {},
      getId: (AudioSettings object) => object.id,
      setId: (AudioSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AudioSettings object, fb.Builder fbb) {
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(2, object.index);
        fbb.addBool(4, object.repeat);
        fbb.addBool(5, object.shuffle);
        fbb.addFloat64(6, object.balance);
        fbb.addFloat64(7, object.speed);
        fbb.addFloat64(8, object.volume);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AudioSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..index = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..repeat = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..shuffle = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..balance = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..speed = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..volume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          );

        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[4],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {
        obx_int.RelInfo<Playlist>.toMany(5, object.id): object.playlistSongs,
      },
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final nextAddedOffset = fbb.writeString(object.nextAdded);
        final nameOffset = fbb.writeString(object.name);
        final imageBytesOffset = fbb.writeListInt8(object.imageBytes);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.indestructible);
        fbb.addOffset(3, nextAddedOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(8, nameOffset);
        fbb.addOffset(10, imageBytesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Playlist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..indestructible = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          )
          ..nextAdded = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..imageBytes =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGet(buffer, rootOffset, 24, Uint8List(0))
                  as Uint8List;
        obx_int.InternalToManyAccess.setRelInfo<Playlist>(
          object.playlistSongs,
          store,
          obx_int.RelInfo<Playlist>.toMany(5, object.id),
        );
        return object;
      },
    ),
    Song: obx_int.EntityDefinition<Song>(
      model: _entities[5],
      toOneRelations: (Song object) => [object.artist, object.album],
      toManyRelations: (Song object) => {},
      getId: (Song object) => object.id,
      setId: (Song object, int id) {
        object.id = id;
      },
      objectToFB: (Song object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final lyricsPathOffset = fbb.writeString(object.lyricsPath);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addOffset(2, lyricsPathOffset);
        fbb.addInt64(7, object.duration);
        fbb.addInt64(8, object.trackNumber);
        fbb.addInt64(9, object.discNumber);
        fbb.addInt64(10, object.year);
        fbb.addBool(13, object.liked);
        fbb.addBool(14, object.fullyLoaded);
        fbb.addOffset(15, nameOffset);
        fbb.addInt64(16, object.artist.targetId);
        fbb.addInt64(17, object.album.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Song()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..path = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..lyricsPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..trackNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..discNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..year = const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
          ..liked = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            30,
            false,
          )
          ..fullyLoaded = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            32,
            false,
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '');
        object.artist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        object.artist.attach(store);
        object.album.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        object.album.attach(store);
        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[6],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final mongoIDOffset = fbb.writeString(object.mongoID);
        final emailOffset = fbb.writeString(object.email);
        final passwordOffset = fbb.writeString(object.password);
        final deviceListOffset = fbb.writeList(
          object.deviceList.map(fbb.writeString).toList(growable: false),
        );
        final primaryDeviceOffset = fbb.writeString(object.primaryDevice);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, mongoIDOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, passwordOffset);
        fbb.addOffset(4, deviceListOffset);
        fbb.addOffset(5, primaryDeviceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = User()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..mongoID = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..password = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..deviceList = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 12, [])
          ..primaryDevice = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '');

        return object;
      },
    ),
    PlayedSong: obx_int.EntityDefinition<PlayedSong>(
      model: _entities[7],
      toOneRelations: (PlayedSong object) => [object.song],
      toManyRelations: (PlayedSong object) => {},
      getId: (PlayedSong object) => object.id,
      setId: (PlayedSong object, int id) {
        object.id = id;
      },
      objectToFB: (PlayedSong object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.song.targetId);
        fbb.addInt64(2, object.playedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.duration);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlayedSong()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..playedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          );
        object.song.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.song.attach(store);
        return object;
      },
    ),
    PlaylistSong: obx_int.EntityDefinition<PlaylistSong>(
      model: _entities[8],
      toOneRelations: (PlaylistSong object) => [object.playlist, object.song],
      toManyRelations: (PlaylistSong object) => {},
      getId: (PlaylistSong object) => object.id,
      setId: (PlaylistSong object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistSong object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.playlist.targetId);
        fbb.addInt64(2, object.song.targetId);
        fbb.addInt64(3, object.order);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlaylistSong()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..order = const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.playlist.attach(store);
        object.song.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.song.attach(store);
        return object;
      },
    ),
    QueueSong: obx_int.EntityDefinition<QueueSong>(
      model: _entities[9],
      toOneRelations: (QueueSong object) => [object.song],
      toManyRelations: (QueueSong object) => {},
      getId: (QueueSong object) => object.id,
      setId: (QueueSong object, int id) {
        object.id = id;
      },
      objectToFB: (QueueSong object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.song.targetId);
        fbb.addFloat64(2, object.position);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = QueueSong()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..position = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          );
        object.song.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.song.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Album] entity fields to define ObjectBox queries.
class Album_ {
  /// See [Album.id].
  static final id = obx.QueryIntegerProperty<Album>(_entities[0].properties[0]);

  /// See [Album.name].
  static final name = obx.QueryStringProperty<Album>(
    _entities[0].properties[1],
  );

  /// See [Album.artist].
  static final artist = obx.QueryRelationToOne<Album, Artist>(
    _entities[0].properties[2],
  );

  /// See [Album.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<Album>(
    _entities[0].properties[3],
  );

  /// see [Album.songs]
  static final songs = obx.QueryRelationToMany<Album, Song>(
    _entities[0].relations[0],
  );
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[0],
  );

  /// See [AppSettings.firstTime].
  static final firstTime = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[1],
  );

  /// See [AppSettings.systemTray].
  static final systemTray = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[2],
  );

  /// See [AppSettings.fullClose].
  static final fullClose = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[3],
  );

  /// See [AppSettings.mainSongPlace].
  static final mainSongPlace = obx.QueryStringProperty<AppSettings>(
    _entities[1].properties[4],
  );

  /// See [AppSettings.songPlaces].
  static final songPlaces = obx.QueryStringVectorProperty<AppSettings>(
    _entities[1].properties[5],
  );

  /// See [AppSettings.songPlaceIncludeSubfolders].
  static final songPlaceIncludeSubfolders =
      obx.QueryIntegerVectorProperty<AppSettings>(_entities[1].properties[6]);

  /// See [AppSettings.drawerOpen].
  static final drawerOpen = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[7],
  );
}

/// [Artist] entity fields to define ObjectBox queries.
class Artist_ {
  /// See [Artist.id].
  static final id = obx.QueryIntegerProperty<Artist>(
    _entities[2].properties[0],
  );

  /// See [Artist.name].
  static final name = obx.QueryStringProperty<Artist>(
    _entities[2].properties[1],
  );

  /// see [Artist.songs]
  static final songs = obx.QueryRelationToMany<Artist, Song>(
    _entities[2].relations[0],
  );

  /// see [Artist.albums]
  static final albums = obx.QueryBacklinkToMany<Album, Artist>(Album_.artist);
}

/// [AudioSettings] entity fields to define ObjectBox queries.
class AudioSettings_ {
  /// See [AudioSettings.id].
  static final id = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[0],
  );

  /// See [AudioSettings.index].
  static final index = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[1],
  );

  /// See [AudioSettings.repeat].
  static final repeat = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[2],
  );

  /// See [AudioSettings.shuffle].
  static final shuffle = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[3],
  );

  /// See [AudioSettings.balance].
  static final balance = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[4],
  );

  /// See [AudioSettings.speed].
  static final speed = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[5],
  );

  /// See [AudioSettings.volume].
  static final volume = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[6],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[4].properties[0],
  );

  /// See [Playlist.indestructible].
  static final indestructible = obx.QueryBooleanProperty<Playlist>(
    _entities[4].properties[1],
  );

  /// See [Playlist.nextAdded].
  static final nextAdded = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[2],
  );

  /// See [Playlist.createdAt].
  static final createdAt = obx.QueryDateProperty<Playlist>(
    _entities[4].properties[3],
  );

  /// See [Playlist.name].
  static final name = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[4],
  );

  /// See [Playlist.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<Playlist>(
    _entities[4].properties[5],
  );

  /// see [Playlist.playlistSongs]
  static final playlistSongs = obx.QueryRelationToMany<Playlist, PlaylistSong>(
    _entities[4].relations[0],
  );
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// See [Song.id].
  static final id = obx.QueryIntegerProperty<Song>(_entities[5].properties[0]);

  /// See [Song.path].
  static final path = obx.QueryStringProperty<Song>(_entities[5].properties[1]);

  /// See [Song.lyricsPath].
  static final lyricsPath = obx.QueryStringProperty<Song>(
    _entities[5].properties[2],
  );

  /// See [Song.duration].
  static final duration = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[3],
  );

  /// See [Song.trackNumber].
  static final trackNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[4],
  );

  /// See [Song.discNumber].
  static final discNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[5],
  );

  /// See [Song.year].
  static final year = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[6],
  );

  /// See [Song.liked].
  static final liked = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[7],
  );

  /// See [Song.fullyLoaded].
  static final fullyLoaded = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[8],
  );

  /// See [Song.name].
  static final name = obx.QueryStringProperty<Song>(_entities[5].properties[9]);

  /// See [Song.artist].
  static final artist = obx.QueryRelationToOne<Song, Artist>(
    _entities[5].properties[10],
  );

  /// See [Song.album].
  static final album = obx.QueryRelationToOne<Song, Album>(
    _entities[5].properties[11],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[6].properties[0]);

  /// See [User.mongoID].
  static final mongoID = obx.QueryStringProperty<User>(
    _entities[6].properties[1],
  );

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[6].properties[2],
  );

  /// See [User.password].
  static final password = obx.QueryStringProperty<User>(
    _entities[6].properties[3],
  );

  /// See [User.deviceList].
  static final deviceList = obx.QueryStringVectorProperty<User>(
    _entities[6].properties[4],
  );

  /// See [User.primaryDevice].
  static final primaryDevice = obx.QueryStringProperty<User>(
    _entities[6].properties[5],
  );
}

/// [PlayedSong] entity fields to define ObjectBox queries.
class PlayedSong_ {
  /// See [PlayedSong.id].
  static final id = obx.QueryIntegerProperty<PlayedSong>(
    _entities[7].properties[0],
  );

  /// See [PlayedSong.song].
  static final song = obx.QueryRelationToOne<PlayedSong, Song>(
    _entities[7].properties[1],
  );

  /// See [PlayedSong.playedAt].
  static final playedAt = obx.QueryDateProperty<PlayedSong>(
    _entities[7].properties[2],
  );

  /// See [PlayedSong.duration].
  static final duration = obx.QueryIntegerProperty<PlayedSong>(
    _entities[7].properties[3],
  );
}

/// [PlaylistSong] entity fields to define ObjectBox queries.
class PlaylistSong_ {
  /// See [PlaylistSong.id].
  static final id = obx.QueryIntegerProperty<PlaylistSong>(
    _entities[8].properties[0],
  );

  /// See [PlaylistSong.playlist].
  static final playlist = obx.QueryRelationToOne<PlaylistSong, Playlist>(
    _entities[8].properties[1],
  );

  /// See [PlaylistSong.song].
  static final song = obx.QueryRelationToOne<PlaylistSong, Song>(
    _entities[8].properties[2],
  );

  /// See [PlaylistSong.order].
  static final order = obx.QueryIntegerProperty<PlaylistSong>(
    _entities[8].properties[3],
  );
}

/// [QueueSong] entity fields to define ObjectBox queries.
class QueueSong_ {
  /// See [QueueSong.id].
  static final id = obx.QueryIntegerProperty<QueueSong>(
    _entities[9].properties[0],
  );

  /// See [QueueSong.song].
  static final song = obx.QueryRelationToOne<QueueSong, Song>(
    _entities[9].properties[1],
  );

  /// See [QueueSong.position].
  static final position = obx.QueryDoubleProperty<QueueSong>(
    _entities[9].properties[2],
  );
}
