// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../core/entities/album.dart';
import '../../core/entities/app_settings.dart';
import '../../core/entities/artist.dart';
import '../../core/entities/audio_settings.dart';
import '../../core/entities/playlist.dart';
import '../../core/entities/song.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5434110965985548662),
    name: 'Album',
    lastPropertyId: const obx_int.IdUid(13, 7618361768251970027),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7032580492777901318),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 407877923627896617),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1723867092633600964),
        name: 'artistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 1626958777364333393),
        relationField: 'artist',
        relationTarget: 'Artist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8887715385877929801),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3924521693914475052),
        name: 'serverId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(21, 4235753723081638949),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5063639271441214345),
        name: 'requiresSync',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(6, 9013398164605295817),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5636332516459031152),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(16, 21833390866547921),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8182695408861448713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7350112739434599895),
        name: 'firstTime',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7187739893577837077),
        name: 'systemTray',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8807803993324951881),
        name: 'fullClose',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2971545764559009366),
        name: 'mainSongPlace',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3530066872263334473),
        name: 'songPlaces',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4299180230132809907),
        name: 'songPlaceIncludeSubfolders',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5824882614796350963),
        name: 'drawerOpen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4258273659752079484),
        name: 'peerNetworkMode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1151355273231320830),
        name: 'peerWifiDataLimitGB',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4994523449491059233),
        name: 'peerCellularDataLimitGB',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1673822122466229522),
        name: 'peerWifiUploadedBytesThisMonth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6328768364523248861),
        name: 'peerCellularUploadedBytesThisMonth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 21833390866547921),
        name: 'peerUploadResetMonth',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 286855446892723846),
    name: 'Artist',
    lastPropertyId: const obx_int.IdUid(6, 7678880629760653732),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4328875806142310070),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5416451551965956234),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8568210031913555152),
        name: 'serverId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(22, 7614771962083118498),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2380292327961155992),
        name: 'requiresSync',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(7, 6366286765168433062),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'albums',
        srcEntity: 'Album',
        srcField: 'artist',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 125102733176896809),
    name: 'AudioSettings',
    lastPropertyId: const obx_int.IdUid(13, 165460848049108724),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5477265908356053087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8073265993596439316),
        name: 'repeat',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1400504775426850532),
        name: 'shuffle',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 544190301642256248),
        name: 'speed',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5535822755287570937),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5466112058997796915),
        name: 'sliderInSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 165460848049108724),
        name: 'pitch',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8253375800311252238),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(16, 2907426317388572025),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8434415855449134709),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3455489451381713443),
        name: 'indestructible',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2645844746166457040),
        name: 'nextAdded',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2530901746877373657),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1802919749950013416),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 966267869899998642),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 881138440698078583),
        name: 'requiresSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5098889426943146136),
        name: 'serverId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(23, 7943714547803203183),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2907426317388572025),
        name: 'songFileHashes',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(9, 7632131054866366746),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 5328859898643810358),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5328859898643810358),
    name: 'Song',
    lastPropertyId: const obx_int.IdUid(28, 5586295309400875881),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8349890911918800237),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5064592112988109331),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4990231509912090547),
        name: 'trackNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1705812540767964011),
        name: 'discNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4172274590478861863),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5072589520708592835),
        name: 'fullyLoaded',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4145861533755825969),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2204895483700977006),
        name: 'artistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 774830058903062476),
        relationField: 'artist',
        relationTarget: 'Artist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7424054812745538720),
        name: 'albumId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 6060959533894279167),
        relationField: 'album',
        relationTarget: 'Album',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1874830640735738982),
        name: 'durationInSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1415657656886012391),
        name: 'likedByUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7039912904383656345),
        name: 'lastPlayed',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5586868054717929816),
        name: 'playCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3835940553080101764),
        name: 'requiresSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 1024957334078684974),
        name: 'fileHash',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(20, 3494203868611330631),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 1880970681925066010),
        name: 'pendingPlayCountDelta',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 5586295309400875881),
        name: 'pendingPlayDurationSeconds',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(13, 9001332223065747901),
    lastIndexId: const obx_int.IdUid(23, 7943714547803203183),
    lastRelationId: const obx_int.IdUid(9, 7632131054866366746),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      8147548360535687209,
      1656493538472770553,
      6143492356218552554,
      4321669200708338290,
      5686730227622637123,
      4825632188467975262,
      9001332223065747901,
    ],
    retiredIndexUids: const [
      3299821873480654513,
      5495534843995516530,
      5875477887538721059,
      2189184110949834609,
      6323886865723491998,
      358579570990390237,
    ],
    retiredPropertyUids: const [
      1158660851052252113,
      7149598354745784686,
      1569902295142124546,
      1008458843636792636,
      5544579394423112026,
      5323548150098807575,
      2943805729086177467,
      5782041773266088141,
      1840321970361704243,
      4814418086711149227,
      7650922049008629566,
      8600891691394737110,
      4543366596315292496,
      1533051777349163043,
      8421888090370908218,
      9200305186945584370,
      3462329237618661875,
      3786128439205850546,
      8350880238422885241,
      4724448620056894215,
      4849993503317089340,
      8760273509754657128,
      4469033242742600143,
      4331356309693753328,
      4313796314850674183,
      2784386784936256907,
      5438557649624740852,
      7588651334738479868,
      3374299748312447501,
      1080393989965147079,
      8769233292901583841,
      7888854975049953792,
      5022077708283063641,
      3042806537210118674,
      5130861840308955545,
      6491925808323369855,
      8372476156145397775,
      6560857396959259464,
      1951961947720040855,
      1712099644485876943,
      398563368122461455,
      2092422769119360865,
      4168045132000032814,
      4471228529824775381,
      3735463316115781249,
      1890088438278972916,
      7438866839967098830,
      4547713415112261797,
      2669617878670335734,
      7010134823570654351,
      8626844870117654806,
      8651225088868707378,
      665571424601739382,
      6469501960945361817,
      2029307388012352250,
      6040705614023113429,
      2306020798377727376,
      1694862551234699842,
      7618361768251970027,
      7678880629760653732,
      5719158023689531142,
      5959721265217084770,
      8997306184455754979,
      1216156411072420363,
    ],
    retiredRelationUids: const [
      1387782578054686999,
      4329599273410235920,
      7460723377333623315,
      1922746581072921885,
      1676580428239258720,
      9083737730595683507,
    ],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Album: obx_int.EntityDefinition<Album>(
      model: _entities[0],
      toOneRelations: (Album object) => [object.artist],
      toManyRelations: (Album object) => {
        obx_int.RelInfo<Album>.toMany(6, object.id): object.songs,
      },
      getId: (Album object) => object.id,
      setId: (Album object, int id) {
        object.id = id;
      },
      objectToFB: (Album object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt8(object.imageBytes!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(7, object.artist.targetId);
        fbb.addOffset(8, imageBytesOffset);
        fbb.addInt64(10, object.serverId);
        fbb.addBool(11, object.requiresSync);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Album()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..imageBytes =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 20)
                  as Uint8List?
          ..serverId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..requiresSync = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          );
        object.artist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.artist.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Album>(
          object.songs,
          store,
          obx_int.RelInfo<Album>.toMany(6, object.id),
        );
        return object;
      },
    ),
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[1],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        final mainSongPlaceOffset = fbb.writeString(object.mainSongPlace);
        final songPlacesOffset = fbb.writeList(
          object.songPlaces.map(fbb.writeString).toList(growable: false),
        );
        final songPlaceIncludeSubfoldersOffset = fbb.writeListInt64(
          object.songPlaceIncludeSubfolders,
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addBool(3, object.firstTime);
        fbb.addBool(4, object.systemTray);
        fbb.addBool(5, object.fullClose);
        fbb.addOffset(6, mainSongPlaceOffset);
        fbb.addOffset(7, songPlacesOffset);
        fbb.addOffset(8, songPlaceIncludeSubfoldersOffset);
        fbb.addBool(9, object.drawerOpen);
        fbb.addInt64(10, object.peerNetworkMode);
        fbb.addInt64(11, object.peerWifiDataLimitGB);
        fbb.addInt64(12, object.peerCellularDataLimitGB);
        fbb.addInt64(13, object.peerWifiUploadedBytesThisMonth);
        fbb.addInt64(14, object.peerCellularUploadedBytesThisMonth);
        fbb.addInt64(15, object.peerUploadResetMonth);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..firstTime = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..systemTray = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..fullClose = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..mainSongPlace = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..songPlaces = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 18, [])
          ..songPlaceIncludeSubfolders = const fb.ListReader<int>(
            fb.Int64Reader(),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 20, [])
          ..drawerOpen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          )
          ..peerNetworkMode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..peerWifiDataLimitGB = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            26,
            0,
          )
          ..peerCellularDataLimitGB = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          )
          ..peerWifiUploadedBytesThisMonth = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..peerCellularUploadedBytesThisMonth = const fb.Int64Reader()
              .vTableGet(buffer, rootOffset, 32, 0)
          ..peerUploadResetMonth = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            34,
            0,
          );

        return object;
      },
    ),
    Artist: obx_int.EntityDefinition<Artist>(
      model: _entities[2],
      toOneRelations: (Artist object) => [],
      toManyRelations: (Artist object) => {
        obx_int.RelInfo<Artist>.toMany(7, object.id): object.songs,
        obx_int.RelInfo<Album>.toOneBacklink(
          8,
          object.id,
          (Album srcObject) => srcObject.artist,
        ): object.albums,
      },
      getId: (Artist object) => object.id,
      setId: (Artist object, int id) {
        object.id = id;
      },
      objectToFB: (Artist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.serverId);
        fbb.addBool(4, object.requiresSync);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Artist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..serverId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..requiresSync = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          );
        obx_int.InternalToManyAccess.setRelInfo<Artist>(
          object.songs,
          store,
          obx_int.RelInfo<Artist>.toMany(7, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Artist>(
          object.albums,
          store,
          obx_int.RelInfo<Album>.toOneBacklink(
            8,
            object.id,
            (Album srcObject) => srcObject.artist,
          ),
        );
        return object;
      },
    ),
    AudioSettings: obx_int.EntityDefinition<AudioSettings>(
      model: _entities[3],
      toOneRelations: (AudioSettings object) => [],
      toManyRelations: (AudioSettings object) => {},
      getId: (AudioSettings object) => object.id,
      setId: (AudioSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AudioSettings object, fb.Builder fbb) {
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addBool(4, object.repeat);
        fbb.addBool(5, object.shuffle);
        fbb.addFloat64(7, object.speed);
        fbb.addFloat64(8, object.volume);
        fbb.addInt64(11, object.sliderInSeconds);
        fbb.addFloat64(12, object.pitch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AudioSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..repeat = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..shuffle = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..speed = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..volume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..sliderInSeconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            26,
            0,
          )
          ..pitch = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          );

        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[4],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {
        obx_int.RelInfo<Playlist>.toMany(9, object.id): object.songs,
      },
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final nextAddedOffset = fbb.writeString(object.nextAdded);
        final nameOffset = fbb.writeString(object.name);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt8(object.imageBytes!);
        final songFileHashesOffset = fbb.writeList(
          object.songFileHashes.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.indestructible);
        fbb.addOffset(3, nextAddedOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(8, nameOffset);
        fbb.addOffset(10, imageBytesOffset);
        fbb.addBool(12, object.requiresSync);
        fbb.addInt64(13, object.serverId);
        fbb.addOffset(15, songFileHashesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Playlist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..indestructible = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          )
          ..nextAdded = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..imageBytes =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 24)
                  as Uint8List?
          ..requiresSync = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..serverId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..songFileHashes = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 34, []);
        obx_int.InternalToManyAccess.setRelInfo<Playlist>(
          object.songs,
          store,
          obx_int.RelInfo<Playlist>.toMany(9, object.id),
        );
        return object;
      },
    ),
    Song: obx_int.EntityDefinition<Song>(
      model: _entities[5],
      toOneRelations: (Song object) => [object.artist, object.album],
      toManyRelations: (Song object) => {},
      getId: (Song object) => object.id,
      setId: (Song object, int id) {
        object.id = id;
      },
      objectToFB: (Song object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final nameOffset = fbb.writeString(object.name);
        final fileHashOffset = fbb.writeString(object.fileHash);
        fbb.startTable(29);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addInt64(8, object.trackNumber);
        fbb.addInt64(9, object.discNumber);
        fbb.addInt64(10, object.year);
        fbb.addBool(14, object.fullyLoaded);
        fbb.addOffset(15, nameOffset);
        fbb.addInt64(16, object.artist.targetId);
        fbb.addInt64(17, object.album.targetId);
        fbb.addInt64(18, object.durationInSeconds);
        fbb.addBool(19, object.likedByUser);
        fbb.addInt64(
          20,
          object.lastPlayed == null
              ? null
              : object.lastPlayed!.microsecondsSinceEpoch * 1000,
        );
        fbb.addInt64(21, object.playCount);
        fbb.addBool(23, object.requiresSync);
        fbb.addOffset(25, fileHashOffset);
        fbb.addInt64(26, object.pendingPlayCountDelta);
        fbb.addInt64(27, object.pendingPlayDurationSeconds);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastPlayedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final object = Song()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..path = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..trackNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..discNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..year = const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
          ..fullyLoaded = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            32,
            false,
          )
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..durationInSeconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            40,
            0,
          )
          ..likedByUser = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            42,
            false,
          )
          ..lastPlayed = lastPlayedValue == null
              ? null
              : DateTime.fromMicrosecondsSinceEpoch(
                  (lastPlayedValue / 1000).round(),
                )
          ..playCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            46,
            0,
          )
          ..requiresSync = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            50,
            false,
          )
          ..fileHash = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 54, '')
          ..pendingPlayCountDelta = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            56,
            0,
          )
          ..pendingPlayDurationSeconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            58,
            0,
          );
        object.artist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        object.artist.attach(store);
        object.album.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        object.album.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Album] entity fields to define ObjectBox queries.
class Album_ {
  /// See [Album.id].
  static final id = obx.QueryIntegerProperty<Album>(_entities[0].properties[0]);

  /// See [Album.name].
  static final name = obx.QueryStringProperty<Album>(
    _entities[0].properties[1],
  );

  /// See [Album.artist].
  static final artist = obx.QueryRelationToOne<Album, Artist>(
    _entities[0].properties[2],
  );

  /// See [Album.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<Album>(
    _entities[0].properties[3],
  );

  /// See [Album.serverId].
  static final serverId = obx.QueryIntegerProperty<Album>(
    _entities[0].properties[4],
  );

  /// See [Album.requiresSync].
  static final requiresSync = obx.QueryBooleanProperty<Album>(
    _entities[0].properties[5],
  );

  /// see [Album.songs]
  static final songs = obx.QueryRelationToMany<Album, Song>(
    _entities[0].relations[0],
  );
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[0],
  );

  /// See [AppSettings.firstTime].
  static final firstTime = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[1],
  );

  /// See [AppSettings.systemTray].
  static final systemTray = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[2],
  );

  /// See [AppSettings.fullClose].
  static final fullClose = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[3],
  );

  /// See [AppSettings.mainSongPlace].
  static final mainSongPlace = obx.QueryStringProperty<AppSettings>(
    _entities[1].properties[4],
  );

  /// See [AppSettings.songPlaces].
  static final songPlaces = obx.QueryStringVectorProperty<AppSettings>(
    _entities[1].properties[5],
  );

  /// See [AppSettings.songPlaceIncludeSubfolders].
  static final songPlaceIncludeSubfolders =
      obx.QueryIntegerVectorProperty<AppSettings>(_entities[1].properties[6]);

  /// See [AppSettings.drawerOpen].
  static final drawerOpen = obx.QueryBooleanProperty<AppSettings>(
    _entities[1].properties[7],
  );

  /// See [AppSettings.peerNetworkMode].
  static final peerNetworkMode = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[8],
  );

  /// See [AppSettings.peerWifiDataLimitGB].
  static final peerWifiDataLimitGB = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[9],
  );

  /// See [AppSettings.peerCellularDataLimitGB].
  static final peerCellularDataLimitGB = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[10],
  );

  /// See [AppSettings.peerWifiUploadedBytesThisMonth].
  static final peerWifiUploadedBytesThisMonth =
      obx.QueryIntegerProperty<AppSettings>(_entities[1].properties[11]);

  /// See [AppSettings.peerCellularUploadedBytesThisMonth].
  static final peerCellularUploadedBytesThisMonth =
      obx.QueryIntegerProperty<AppSettings>(_entities[1].properties[12]);

  /// See [AppSettings.peerUploadResetMonth].
  static final peerUploadResetMonth = obx.QueryIntegerProperty<AppSettings>(
    _entities[1].properties[13],
  );
}

/// [Artist] entity fields to define ObjectBox queries.
class Artist_ {
  /// See [Artist.id].
  static final id = obx.QueryIntegerProperty<Artist>(
    _entities[2].properties[0],
  );

  /// See [Artist.name].
  static final name = obx.QueryStringProperty<Artist>(
    _entities[2].properties[1],
  );

  /// See [Artist.serverId].
  static final serverId = obx.QueryIntegerProperty<Artist>(
    _entities[2].properties[2],
  );

  /// See [Artist.requiresSync].
  static final requiresSync = obx.QueryBooleanProperty<Artist>(
    _entities[2].properties[3],
  );

  /// see [Artist.songs]
  static final songs = obx.QueryRelationToMany<Artist, Song>(
    _entities[2].relations[0],
  );

  /// see [Artist.albums]
  static final albums = obx.QueryBacklinkToMany<Album, Artist>(Album_.artist);
}

/// [AudioSettings] entity fields to define ObjectBox queries.
class AudioSettings_ {
  /// See [AudioSettings.id].
  static final id = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[0],
  );

  /// See [AudioSettings.repeat].
  static final repeat = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[1],
  );

  /// See [AudioSettings.shuffle].
  static final shuffle = obx.QueryBooleanProperty<AudioSettings>(
    _entities[3].properties[2],
  );

  /// See [AudioSettings.speed].
  static final speed = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[3],
  );

  /// See [AudioSettings.volume].
  static final volume = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[4],
  );

  /// See [AudioSettings.sliderInSeconds].
  static final sliderInSeconds = obx.QueryIntegerProperty<AudioSettings>(
    _entities[3].properties[5],
  );

  /// See [AudioSettings.pitch].
  static final pitch = obx.QueryDoubleProperty<AudioSettings>(
    _entities[3].properties[6],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[4].properties[0],
  );

  /// See [Playlist.indestructible].
  static final indestructible = obx.QueryBooleanProperty<Playlist>(
    _entities[4].properties[1],
  );

  /// See [Playlist.nextAdded].
  static final nextAdded = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[2],
  );

  /// See [Playlist.createdAt].
  static final createdAt = obx.QueryDateProperty<Playlist>(
    _entities[4].properties[3],
  );

  /// See [Playlist.name].
  static final name = obx.QueryStringProperty<Playlist>(
    _entities[4].properties[4],
  );

  /// See [Playlist.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<Playlist>(
    _entities[4].properties[5],
  );

  /// See [Playlist.requiresSync].
  static final requiresSync = obx.QueryBooleanProperty<Playlist>(
    _entities[4].properties[6],
  );

  /// See [Playlist.serverId].
  static final serverId = obx.QueryIntegerProperty<Playlist>(
    _entities[4].properties[7],
  );

  /// See [Playlist.songFileHashes].
  static final songFileHashes = obx.QueryStringVectorProperty<Playlist>(
    _entities[4].properties[8],
  );

  /// see [Playlist.songs]
  static final songs = obx.QueryRelationToMany<Playlist, Song>(
    _entities[4].relations[0],
  );
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// See [Song.id].
  static final id = obx.QueryIntegerProperty<Song>(_entities[5].properties[0]);

  /// See [Song.path].
  static final path = obx.QueryStringProperty<Song>(_entities[5].properties[1]);

  /// See [Song.trackNumber].
  static final trackNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[2],
  );

  /// See [Song.discNumber].
  static final discNumber = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[3],
  );

  /// See [Song.year].
  static final year = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[4],
  );

  /// See [Song.fullyLoaded].
  static final fullyLoaded = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[5],
  );

  /// See [Song.name].
  static final name = obx.QueryStringProperty<Song>(_entities[5].properties[6]);

  /// See [Song.artist].
  static final artist = obx.QueryRelationToOne<Song, Artist>(
    _entities[5].properties[7],
  );

  /// See [Song.album].
  static final album = obx.QueryRelationToOne<Song, Album>(
    _entities[5].properties[8],
  );

  /// See [Song.durationInSeconds].
  static final durationInSeconds = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[9],
  );

  /// See [Song.likedByUser].
  static final likedByUser = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[10],
  );

  /// See [Song.lastPlayed].
  static final lastPlayed = obx.QueryDateNanoProperty<Song>(
    _entities[5].properties[11],
  );

  /// See [Song.playCount].
  static final playCount = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[12],
  );

  /// See [Song.requiresSync].
  static final requiresSync = obx.QueryBooleanProperty<Song>(
    _entities[5].properties[13],
  );

  /// See [Song.fileHash].
  static final fileHash = obx.QueryStringProperty<Song>(
    _entities[5].properties[14],
  );

  /// See [Song.pendingPlayCountDelta].
  static final pendingPlayCountDelta = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[15],
  );

  /// See [Song.pendingPlayDurationSeconds].
  static final pendingPlayDurationSeconds = obx.QueryIntegerProperty<Song>(
    _entities[5].properties[16],
  );
}
