name: Build and Publish Binaries

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: apk
            build_cmd: flutter build apk --release --dart-define=API_BASE_URL=https://www.bt-app.com/api/v1 --dart-define=WS_BASE_URL=wss://www.bt-app.com/ws/signaling
            artifact_name: music-player-android
            artifact_path: music-player-frontend/build/app/outputs/flutter-apk/app-release.apk

          - os: ubuntu-latest
            target: linux
            build_cmd: flutter build linux --release --dart-define=API_BASE_URL=https://www.bt-app.com/api/v1 --dart-define=WS_BASE_URL=wss://www.bt-app.com/ws/signaling
            artifact_name: music-player-linux
            artifact_path: music-player-frontend/music-player-linux.tar.gz

#          - os: windows-latest
#            target: windows
#            build_cmd: flutter build windows --release --dart-define=API_BASE_URL=https://www.bt-app.com/api/v1 --dart-define=WS_BASE_URL=wss://www.bt-app.com/ws/signaling
#            artifact_name: music-player-windows
#            artifact_path: music-player-frontend/music-player-windows.zip
#
#          - os: macos-latest
#            target: macos
#            build_cmd: flutter build macos --release --dart-define=API_BASE_URL=https://www.bt-app.com/api/v1 --dart-define=WS_BASE_URL=wss://www.bt-app.com/ws/signaling
#            artifact_name: music-player-macos
#            artifact_path: music-player-frontend/music-player-macos.zip

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libsecret-1-dev libjsoncpp-dev libmpv-dev mpv


      - working-directory: ./music-player-frontend
        run: flutter pub get

      - working-directory: ./music-player-frontend
        run: ${{ matrix.build_cmd }}

      - if: matrix.target == 'linux'
        working-directory: ./music-player-frontend
        run: tar -czvf music-player-linux.tar.gz -C build/linux/x64/release/bundle .

      - if: matrix.target == 'windows'
        working-directory: ./music-player-frontend
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath music-player-windows.zip

      - if: matrix.target == 'macos'
        working-directory: ./music-player-frontend
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../music-player-macos.zip *.app

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

  deploy-to-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./downloads

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./downloads/*"
          target: "/var/www/music-frontend/downloads"
          strip_components: 1