name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'music-player-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      lib-changed: ${{ steps.filter.outputs.lib }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            lib:
              - 'music-player-frontend/lib/**'
	      - 'music-player-frontend/test/**'

  test:
    needs: check-changes
    if: needs.check-changes.outputs.lib-changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - working-directory: ./music-player-frontend
        run: flutter pub get

      - working-directory: ./music-player-frontend
        run: dart run build_runner build --delete-conflicting-outputs

      - working-directory: ./music-player-frontend
        run: flutter test

  build-and-deploy:
    needs: [check-changes, test]
    if: always() && needs.check-changes.result == 'success' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - working-directory: ./music-player-frontend
        run: flutter pub get

      - working-directory: ./music-player-frontend
        run: flutter build web -t lib/main_web.dart --base-href / --release --dart-define=API_BASE_URL=https://api.bt-app.com/music-player --dart-define=WS_BASE_URL=wss://wss.bt-app.com/music-player/signaling

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /var/www/music-frontend/*

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "music-player-frontend/build/web/*"
          target: "/var/www/music-frontend"
          strip_components: 3
