name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'music-player-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - working-directory: ./music-player-frontend
        run: flutter pub get

      - working-directory: ./music-player-frontend
        run: flutter build web -t lib/main-web.dart --release --dart-define=API_BASE_URL=https://www.bt-app.com/api/v1 --dart-define=WS_BASE_URL=wss://www.bt-app.com/ws/signaling

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /var/www/music-frontend/*

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "music-player-frontend/build/web/*"
          target: "/var/www/music-frontend"
          strip_components: 3